apiVersion: v1
kind: Secret
metadata:
    labels:
        cnpg.io/reload: "true"
    name: velocita-news-staging-postgres-credentials
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    password: ENC[AES256_GCM,data:pw7w2u7ydB027STKRQrx46Gu/z6hNKCW,iv:WKDCL6cSa/XGSbuw8JVDMw/eg+NPgHS1KFaOY9oOqOw=,tag:X05P9g17is0NaRJHSAJv7g==,type:str]
    username: ENC[AES256_GCM,data:9iGXjTd+prZGQzcz9W3jwmwhfP+behRK2t1dXEA=,iv:3FOJq5SQsGqQQ8ytPYQXXq3NUCS+uRF09RXyz/A+kwQ=,tag:qmFRd04EOUryvhI7XSH9VA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByY3hwb1RQSE8rbFlTZ0E0
            eVJGck9Va1V4MjdyRXVQeGs2eGtKS203MjJFCmw3M1hUNDcrbGZYdVM2TW13MzF5
            TEp3RVZPdkVoMlBlL1EwSHpPMTlaK00KLS0tIHZENXVKU2NhTS85MVZkR1BoazV6
            QUQxRVNyQlp3TElCMCtvTVl5VXFaWTgKODbzHj9nZDrCLmzkkUkHAa7cf1ElsTSV
            EQC9Qga6RQtjjs+EQc6JH53couiPJclGNVXqoNIJCD9LGh7MEvkfBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yfmz6900gp85qvse6pdd53h0c698jeh7pltmhtcpgse4duncqaqq9j2k23
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T11:06:20Z"
    mac: ENC[AES256_GCM,data:Xfwiw+IZO2n4PaFXJrlvadT9iZ0ugSe+81I2ccIPgd1258qlUTcsSRYbBS0FS6+m3UIRMZoPI7cw75QsGqa68H3vi6oXFpI8PQJn/mcsWyCFaG5nJse8yHElZl8RM34ornROIDDSXgx0K6K9ZSd9swk6Jq9ipW76hGoO+b5vk4g=,iv:zgXofB+UT5wLUNSAxIph3stikOKnZF8MWu0YhCVhDYs=,tag:LPqtScC69oZDaRlFs8CXSw==,type:str]
    version: 3.13.0
