---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: readability
  namespace: default
  labels:
    app.kubernetes.io/name: readability
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: readability
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: readability
    spec:
      imagePullSecrets:
        - name: regcred
      tolerations:
        - key: node.kubernetes.io/server-usage
          operator: Equal
          value: readability
          effect: NoSchedule
      containers:
        - name: readability

          image: "margarinas/readability:latest"
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: READABILITY_MAX_CONCURRENCY
              value: "1"
            - name: READABILITY_MAX_HTML_BYTES
              value: "8000000"
            - name: READABILITY_BROWSER_OPERATION_TIMEOUT_MS
              value: "30000"
          resources:
            requests:
              cpu: 2000m
              memory: 4Gi
            limits:
              cpu: 3700m
              memory: 7000Mi

