apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
        "auths": {
                "https://index.docker.io/v1/": {
                        "auth": "bWFyZ2FyaW5hczpUNHI3MmplNWZGM3NQMFQkYWo="
                }
        }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: pxc-db-secrets
type: Opaque
stringData:
  clustercheck: '4GMc4nH9I5d4mwqWR6'
  monitor: '7Xge6PvkU3xQpQP8EJ4m'
  operator: 'XzBsEHsaSY8Eyq84ZVBd'
  proxyadmin: 'DuaaJSnvQTWP8bZBUBLk'
  replication: 'dYYLquUMpLLL5GeeFAyr'
  root: 'e5sX5swpCrma8TpPNdsx'
  xtrabackup: 'ar7ZjjfWNTDxtmFMHYZH'
---
apiVersion: v1
kind: Secret
metadata:
  name: pxc-db-connection
type: Opaque
stringData:
  # same as root username in pxc-db-secrets
  username: 'root'
  # same as root password in pxc-db-secrets
  password: 'e5sX5swpCrma8TpPNdsx'
  # default is pxc-db-haproxy.infrastructure.svc.cluster.local
  endpoint: 'pxc-db-haproxy.default.svc.cluster.local'
  # default is 3306
  port: '3306'
---
apiVersion: v1
kind: Secret
metadata:
  name: velocita-db-backup-s3
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "00323b62bd98d890000000001"
  AWS_SECRET_ACCESS_KEY: "K003lelJUVAMTfgdiGyfLnX0j+fcVAg"
