---
apiVersion: v1
kind: ConfigMap
metadata:
  name: velocita
  namespace: default
  labels:
    app.kubernetes.io/name: velocita

data:
  APP_DEBUG: "true"
  APP_DOMAIN: "velocita.motorsniper.lt"
  APP_ENV: "development"
  APP_NAME: "Velocita"
  APP_URL: "https://velocita.motorsniper.lt"
  AWS_ACCESS_KEY_ID: "00323b62bd98d890000000001"
  AWS_BUCKET: "velocita-storage"
  AWS_DEFAULT_REGION: "eu-central-003"
  AWS_ENDPOINT: "https://s3.eu-central-003.backblazeb2.com"
  AWS_URL: "https://f003.backblazeb2.com/file/velocita-storage"
  BRANDWATCH_API_ENDPOINT: "http://brandwatch/api"
  BRANDWATCH_API_KEY: "1|AHAGDhdEWpUybRG4pT3kIUEEqt5PHQ7qZRJuVpwC"
  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "redis"
  DB_CONNECTION: "mysql"
  DB_DATABASE: "velocita-db"
  DB_HOST: "pxc-db-haproxy.infrastructure.svc.cluster.local"
  DB_PORT: "3306"
  DB_USERNAME: "velocita-db-user"
  GOOGLE_PROJECT_ID: "expanded-lock-279422"
  GOOGLE_REDIRECT_URI: "https://velocita.motorsniper.lt/oauth/gmail"
  IMAP_DEFAULT_ACCOUNT: "default"
  IMAP_ENCRYPTION: "ssl"
  IMAP_HOST: "apelsinas.serveriai.lt"
  IMAP_PORT: "993"
  IMAP_PROTOCOL: "imap"
  IMAP_USERNAME: "velocita@motorsniper.lt"
  IMAP_VALIDATE_CERT: "true"
  INVOICE_VELOCITA_PREV_INVOICE_NUMBERS: "611"
  LOG_CHANNEL: "stack"
  LOG_LEVEL: "debug"
  MAIL_ENCRYPTION: "tls"
  MAIL_FROM_ADDRESS: "info@velocita.lt"
  MAIL_FROM_NAME: "Velocita"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_MAILER: "smtp"
  MAIL_PORT: "587"
  MAIL_USERNAME: "linas@velocita.lt"
  MEILISEARCH_HOST: "http://meilisearch:7700"
  OPENAI_REQUEST_TIMEOUT: "120"
  PHP_MEMORY_LIMIT: "512M"
  PHP_POOL_NAME: "velocita_php"
  QUEUE_CONNECTION: "redis"
  REDIS_HOST: "dragonfly.default"
  REDIS_PORT: "6379"
  SCOUT_DRIVER: "meilisearch"
  SCOUT_QUEUE: "true"
  SESSION_DRIVER: "redis"
  SESSION_LIFETIME: "120"
  SSL_MODE: "off"
  TELESCOPE_QUERY_WATCHER: "true"
  PHP_OPCACHE_ENABLE: "1"

