apiVersion: v1
kind: ConfigMap
metadata:
  name: velocita-pgloader
  namespace: default
data:
  velocita.load: |
    LOAD DATABASE
         FROM mysql://velocita-db-user@pxc-db-haproxy.default:3306/velocita-db?useSSL=false
         INTO postgresql://velocita-db-user@postgres-rw.default:5432/velocita-db

     WITH include drop, create tables, create indexes, reset sequences,
          foreign keys, downcase identifiers, uniquify index names,
          workers = 4, concurrency = 1

      SET PostgreSQL PARAMETERS
          maintenance_work_mem to '128MB',
          work_mem to '16MB'

      SET MySQL PARAMETERS
          net_read_timeout = '120',
          net_write_timeout = '120'

     AFTER LOAD DO
       $$ analyze; $$;
