apiVersion: v1
data:
    password: ENC[AES256_GCM,data:omkmDmyUE3cB2dopdR6l71rNoNKvAejO,iv:KtTkJJ26+/gdRSG0gt+xV94Du3L1HDia06+8/gG7Ek0=,tag:CfI5tmT5ozy/UoF1x5mK/w==,type:str]
    username: ENC[AES256_GCM,data:tTvZDniFLU5HnIFrVpYEoSH/oaqXFj60,iv:q76OUPTG5ZvBIQZ4+A/wQoMN/84iH0ezub0GPGTAMrY=,tag:5T14Yg0+6JgO2FKqXTc5Xg==,type:str]
kind: Secret
metadata:
    labels:
        cnpg.io/reload: "true"
    name: velocita-postgres-credentials
    namespace: default
type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsOW9DbXhuR2xaTTl2bjZy
            NHJwb0J6TWdBRWdYSmJmdWR1VzhYd3NVVER3CldLaEpIcWNoa1FkN25mcGlrMFZJ
            dTdMZS95Q3NlVGZmU0Q1OE5pNENyWUkKLS0tIGNUbysrWXdnWC9iWWpja3dwZkll
            NlBmaVFvWWZSWEw1VUV5Q1V1VmNVRWMK4/+H5FcrWsqz8EfEGKsgRsAmhrD/hldM
            FetdHgxvkPOiljAMj4A10zZgMFb5QMlcIlIaboQSre8OPs+s5R5AEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yfmz6900gp85qvse6pdd53h0c698jeh7pltmhtcpgse4duncqaqq9j2k23
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-12T20:35:02Z"
    mac: ENC[AES256_GCM,data:JmYv77cQeq7+0yzlTtKxAalhfJoIfn6jyKWXZMIob+5XQfhnF2ZhxGMcIYb9oCznkf2DzSS4jwpU5GlSPeeJxol9ACcOdgWRpYJdWB2KpCG7U6xidNwRaTRCtDstioLsGuNKjpcrlGWNrC3Tw1soCGxXt/ira+eD/VFxaEfPuP8=,iv:YE5PWThXY/2dKXORrmSXS9mPSMOvChAp0v9rrP+ZL04=,tag:9aip3M88c0xXVVUZaM4Kdw==,type:str]
    version: 3.13.0
