apiVersion: v1
kind: Secret
metadata:
    labels:
        cnpg.io/reload: "true"
    name: velocita-postgres-credentials
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    password: ENC[AES256_GCM,data:EHMwytAUjXpXzVcHrkMcwA==,iv:23mRVN4Q+DZeYdUvrWlG7mjH7HDz5dKVW4CUh2mWh+Q=,tag:ZHRagqtFmBTDyNG4bdhKtw==,type:str]
    username: ENC[AES256_GCM,data:5QZrEk/gXBlo00P4EN5t4w==,iv:6Fs1H/i9lc+6HTqtR1Gn+gU9AU5HVUkASpjTAljA0so=,tag:zfGqBFWsTXEWDVUOI0dO8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SVNTZ29MUS9tS2NsVEcw
            dER1Zzc4SG5YQ0pXai9yTXMyMHgyZHY4eUhZCm9jMzVzQlU2U0I1Q2FDSVZWbGQx
            VTBUbUU3dmhRRHZDeXFWVi80aXVTSVkKLS0tIGVTZlduNm1OQmtnbDBvMkorVUdG
            Qk5IMGo0SEJLU2Q2V2puM0NzLzRta1UKNKVebi7alCejaV74FTRHprqEvb4iWZu3
            iFO29HAbfQ8MWRKmKZHLWfOmwICqkIlNgI2V0INXPZ2Ip7ewUf/YBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yfmz6900gp85qvse6pdd53h0c698jeh7pltmhtcpgse4duncqaqq9j2k23
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T12:11:08Z"
    mac: ENC[AES256_GCM,data:rOHR0j2J4yLh+TaaAws2nUHHiQguDP6Q3PQT7Psfmz/84PDEmOCEi2ICMb/FQKjk/u1QYrbcFauaGZT5+pwr+nui7HOnxwV7HNna0GLsht27ADKkciOAEysA/rn2BHqFe+riLIr/31yTmURJK+qZpja6reHZv6DNhAa368JerRk=,iv:mQk0m8DQJ7retGfDXr+D2l8nc/zPh4iJ9aC5mbwNiUU=,tag:44ppeMuKdM25LK1i5zVuTw==,type:str]
    version: 3.13.0
