---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velocita-postgres-credentials
  namespace: default
spec:
  encryptedData:
    password: AgCSp4derynAQznyHztCIvFrlINPUIFE/1glk7FyPCGC7+69vZ4bPjjf0msN4P8wHLxASk9aaqTkWKDHm7efKZfYnLzHx2d4u1CnvnOHk+t8SHEf5zlSry0nh8ReAnS+gcB8ty8Tt1rFlDqVcINMkryzX2fPD1/UfsobwUUoMEVezK+g+cUAEES91WAAgVemVy/Z3B+EwabFgo0UBZvAkGPShTU2JZPITNk2qWDGgQh963Vc508VIHnGO1s0wSkJDCxhHylXtvKB3IpDur81bqfXU7SMR7wYfO8Eo6mtlPwuqWPqc2mCsGLyLZEn2gpsV3p6v6tgQ+QLYiaKxMJAL63s9WOwY4Br8oFuYphppJFMo565jN/Tx9kC2nHxdxtwwsb8aEU0M2zsnO0dGpxliBVXn4Y6bKdDfJ3Jcm31Pexw5YEQHrwCMz+iNn+2rB1ftbzuGfpihyVTD7KrSa1JSVoMJSLd3KHP0k/QNFWCkG64c1jM9J3TZQOAIW1KOB2TRa6BvJMVDJn6KufliqoFUjrjdWZaRz56S1We+o/sMF7bkAGAnaxqzxiSiRpjdmcI0CaLPnRWF9akFNoP9b3K71fEgoX/iDN1PZ8k5aMnE0eI2iFJyYz+EbBVrI1oVYuZYNxFMZRRB1tD7S0JB71HDYbPG3iUnM9xgrC/ZMy/kTZXlEsnsjfj8l74IokJ7Rx6Ve1M1tLwCKssIXZ9fFZTDEhi
    username: AgBjQzYk5UL7cFSW5YMN0kjCmEBqcNBugGvszKOSxCtRnyJXM7i4Z5JKyGV1u8fGFQVLPNOMvLh5QslMMgLiR6+MnEKlfGQ0UDaGdowVfdNklrG7F6Y4wH/XjbCxc4V7gp/pzTwTq9hEsNplpemwNVn10b/Q56l6pt8G1VOKmh3h+JTIRB9Mu4PA8tvWlmrEfMll30HVlJayfBPUvhiRU729G6eVrKqvRYHib1vwabpG+Gz1EGUHfcVnvWupNJXYApL0ojJqRIYiNaa0KA4A5huDLC5Do8GO+xvJAt5LpIcKDK4jwayzwU8EzPqWbUrx074/KT5mpXmIKIT5FVDcDkTfNydEDsanP3FY1LZ9raBptrhEOr4uP0E8YgPioeqqnnrkdJsauJVuT8n/qqJfhjrruMjxIJIpj1To8eaw6RZ61G/A4VLToCEHH2SGWS40Kv1ZTISUjcE9OtEqLHu9IuMIB3WTGMXcVeeVWqYq4lZMpZmQXkt+v5cySjvc2rdZ5WdqWFe2yMsMDlJqE716oBj8J7zA21Uc08Pug84XzSb24D0klpP7whfYbQh1qSy67XX7UanlZ0+zKgUknbemR+HcWaejQqKTFz1TwDrJiT2dwsyiVET6K0wyYW/+ffsEv8iOaROfgXbWpROKM/VXg985fO2tyOiXk7GoZRZY1TD1jI2Ue7XcNT9qoJ7t4xW8NRU0rBHlhTqDAOslzixYOa8f
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: velocita-postgres-credentials
      namespace: default
    type: kubernetes.io/basic-auth
