---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velocita-postgres-credentials
  namespace: default
spec:
  encryptedData:
    password: AgAg4UQn9acuvk1EUmGmlHsBxDVHtT/x6dJkGkygT0a+Y/I+Gs+D2en+Jgn+/aeygeBNtRM0T6pUU3nZTYBeDt9jIR3Zj/L/DkYRnNVVInSox7+Itag6RbaUlthfmKWVqr4rnDZy7dpYwsX9MfXfa9l3QjHldPVnHkIjdj1ruMUehI57/8WqhEuEQ5+h20lXyjEYKyH2bYpwgw74YidFYdFDtC4AGlQ92rQm2XQYGhC9TjVVSbK1JQsOEdLXyfz75qG90uC1ga4jgzsJ/DvFedHDJkNY4fkWKjDk28UYjXUYAfzrXlwNesBotnX8ZMFyDWKlvzHpvDiD2E2Y1tDPjHK6kGSs29YGHo8Zjxwkl7MX+nVdd2j0n2wYtPFKjzz5T0GELdrx889Yi4KJfioI7xCAN/5qH1nmE7OtAWm2lvuG73HteCYpZADHVf5v/RgymGz5kvES8mswXAMuNCvWS/5Eqto6kwaO0m/2sMsw8BA49gY8YHFCsqE5bmeEDVSPDKoHrR5utY1F4FsZhW+9CVqyAJNOsh7virImGCsAz+GU1667R8EIskmDoPA6yfQB0Xd//8iQCRvWXgYHqkIPxZI+LkntqJzr1BSvZIRIrJ2+QKeG0zYQkcdecSdzuJhFFhp+e044cr04b34mrua/XkAYFJRCST2yigPrZYSAQnznVekGYt6gesInX/hRtcZsvhI/iL828VKeiftF4yW8whLO
    username: AgAzWe7QUorEFdyDzp8DTbQx2YBTLr0XAsQ//OQKvYOWvro2RdjyN5hBq0AZK8xDcTn3UiG/ku3FK9CaLCkiH84FpFgj4d0vWtAf60BkjTHnXz9GbM3AmRepHzhBUTPIgdkU96y3cbHyYJjlFK2RxjHDngHRiSIC3RBH6geVzwcsOwLe/hl2E1hn1yarNfVqDJnXsO0gn/cewkWY1CPU34zWTFshSplxxfI9+B82ocd1ZCQs1PDr91QWPH7OLnI5Iv1tEssFJhbwOPGs9BOexPVkwPS6H855XfJausPqwASoFwVoF0/vIs3sndTdDgzAJ4fio7QIK3Ssqvsti7w0znuYo6hj7G4MBh5YgfOu5CR08jhfV3gNWYriDDjrwqMpOZyqXJ35vz9fxBGbQSIetB96LfgSc8hhUjknmdMKTpzXmqLyo8zt0zHZnILhUAwNcaTCJjFU8bRXj5Bm3ymfW2o0itjuZf6wt3K2oOpufSZz/tsIB4+Pj1aq8lwNUu8jFv4HngXq0nJZlk8HwP1MV0a0x9b2OPi+dYU+7m9BYik4DDqQj+Q0mNlr01ZsHYrzKgw5VKM8jMuX6pzodCzwnbWW7MvO47frWbXM4e4n0BI8CIbBNw84ZXzne4imbTC2tTBDbeGh7hK41FU0eY0zB2EHSXC4hTFYQxZs4D41tgQ37rsQmWle4PclwkXXXprWXGVdx/zD0LIa8qHEVl8e6Mza
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: velocita-postgres-credentials
      namespace: default
    type: kubernetes.io/basic-auth
