---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velocita-postgres-credentials
  namespace: default
spec:
  encryptedData:
    password: AgAYGCvjhERt9casPwsr1TgWC0ZVBzrDhME2H7JKDrnWFH4koDIrXABkRP1FMmE3at8m/OB54rvIs0HfTIZ4gDi/YG5cj5triBPQgJHmMVdMaeH6Gzu2NEESx5scsDmB79TGGKpwsU/KTuBjPtw633bZtaAiaxkCpwVpkYlkUam+aedFjiqOMfAPmsbxkniqSeDcs/MLzXlrVvSexDPzsAtTxclC8pERubtYdDDxwjQfL/2BqFaNyQKp7MkHFHFb2ibvghtTg5YrR7Q+iT5bFgO4jQ0stA7VOfR//FZHTTvPSejGQnzRGFW2WMr2ZGHbhaYigmSGDCe61CYscKZAdwvVcqaPI7BmsfJ0rRwFmmfCrjsEX+i3y9tEE3sqd7UsVqGTebouhQsha52u5MCr4VkcqIQZM5Ch9/DuzUVwGj1f1wmjae7LXuVMxfgneD6w/YkZlHfnBAc8aehbecPoK8D5E/QH8WvHN6v0XsXLQDlIYlHbegfUQJhCg18BlnTzelfBXsZ1yEfNBnAWbz8YmaBmBgf0efTmHA/H4CbL2NvGVreEiuL7xCM0VW0KU50SN4v5OaDdNqEySG3KpE51Ovl/zcYj2+LSmQPtO222vSYtbJNy1f51/TfNvT4zBCnleEstpvXZn2y8Skk0ls0xQ9UYCyqKO8mrhnpQhP4duZ8eTlMKc8UGCk1r/yxk8B1pAFsM47ZPVZjXcnVCwGCYDnSU
    username: AgBjYKsjtFjXPUZP08OVcXNAGKnfEQkiRKiUG+gcoh6i0bFG9ruHRuWdK0RWFtGetf5qbbAfwQ2YlZleoD7F+g7paHBfdItVTDtITihbBobnHSt1JeoaUADuriMEHdakgBe4b0Tf7VwITy8ZdkEZWM5pJbAOc0piMU8P7ppFzpvv5PxjzHblKjsvP8wW6Oxj81o3TZm4iJKxPWiFHYkgp83hf/rFqL5AL0ek6xLmeWm4vIovS0RzL2+HeFLCtdn/13F/jikXe5xePnvDGgN2DGPmIUSjrJEBUIG48qUsUYM+hFPkr2Bjpa7VVupYBcaaFVHD5cGFmELK90kvjnuRis22VKY5ElPf9FRnpz/RIVHCOXc2W3UZBPe2Mce0tIR09WcXZIGMaCjUtLehKavm4eNimd6bU2n/RmKW8sYUTkXdatniMn0PIuN6lva9HQPvfxIBdSIUsWE8hR0mXyhrhngvrwQo3QTF5eXr/6EoURgkAk1pq1EdnxXpP1gYu2Rxt+PXLvtHjlmaZ5d054RZCVdttci0sIlu45OE9eHkdAnkwqPFPCm+qQrwTg1ZOydydjPsEX5dImhdNrqgR1a7EwJUAAsN4q8AZ0hxDRrpD/Dnx6+C4zMgCKErF337yBsExi0pdfh+gcd+RNyh8amcnGSoMqwzCHA3G50rIXmK0Gl3CYcF3Sxw9MhskZBZXl1hSPKqxOj30t19fI3VFKuvrVIM
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: velocita-postgres-credentials
      namespace: default
    type: kubernetes.io/basic-auth
