apiVersion: v1
kind: Secret
metadata:
    name: velocita
    namespace: default
stringData:
    APP_KEY: ENC[AES256_GCM,data:wfFBoinqw6nVF1Mmk4fhwgVdaT4WZ3ddSBxc+5qhY1cyrfQti6KnknGK4MJoFusKU8Va,iv:t10O+sBmy4nXVWWbdtq+siUp3hW0JVehhRxqALUdkks=,tag:2DzltavbhJP6NPIMw7z9Fg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:L/AuOQEH1bmBqt6pTx1m8kKlcAbwjJSgtOMgA82bUg==,iv:ApEnjhqWGj4QwcNUqkDTPYaAZ5+j4nmwplh9Bx8GMYk=,tag:RhNTZ5vJL7fGDYV72IE2Uw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:OqrDV3SSJcJOWjOtg9FhpQ==,iv:R+1UPuPTemFlWtV0mFOE2rNRJ38zL3CaDSOUBvhrZrE=,tag:GsjoWKH6F87W9yNuOKg8EQ==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:B51AUiLicR8czb2NJsBxZkp/TF5pTP22EAuTUKVIcw4uy4ICjN04eoirvzLT0fYMgs8K8lbEeRRIdoIROxG67s3S+53IAyI=,iv:Zq8iSWrueaviCZAioBdcOJRDcmClNel+MB0iPOo56Kc=,tag:mlybh7VMh1kcZRV5/bmjRw==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:tsg7qzHka112PJ9QYuBAsDJ0uU8K+gNSIvlYWMAJEKsz1lI=,iv:Y9kFMKUtowGHybXyXPcUoBbUyUDpduha1JqgWeOt2Bw=,tag:8lktb5x6Wa5GH+fHExY1Sg==,type:str]
    GOOGLE_TRANSLATE_API_KEY: ENC[AES256_GCM,data:QP8oxki2RGoD0CpbaHXYsVSP0X9GfEdPSDhiPo2xEYSpV43pHgg0,iv:222sQ0DXgnA8+bWA+rmh1OdAPWgcsDpbwCwoHj1JSl0=,tag:1SVdy3lH/gjZNKKMpFnsXA==,type:str]
    IMAP_PASSWORD: ENC[AES256_GCM,data:/+RxUdBa/tybN8ris1ckkQ==,iv:/3jj5Wpgd1HycPelFvBSsJrUYRMB/57eC2nm+jjErxE=,tag:7dUM3cpxf5i5o/Ph3pmq6w==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:R7AwJKBuUZv0UUK0mnrHGw==,iv:9A849NxsFjupnQjRfO0sqaQT0bW3L2jw8gwvV4aN8ms=,tag:dxiaJFIQj9XS0uCOb1lhEw==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:w/JZPS1TNkZUeQAADqmaY+F5PAOvjfXhVZaZCC0VukGG61YWd6yt4AGLZe/oCMokyVVX,iv:CF7rPyQ0NDPZeJ6uxAsolf2ZA6jzyGLx3DFFCeCK5lk=,tag:hty9vjr2X/4NXdXo6I9M7g==,type:str]
    TRELLO_API_KEY: ENC[AES256_GCM,data:BUJVKww+Spurgyq5yTDeVZhleIuqE2KsPCIDU2LTdDQ=,iv:IdYL1apWXmRV5NyouZOxZwOSs2EakvTGpTump9AoLNs=,tag:lIUXs1+lELrezHB9u/JKQw==,type:str]
    TRELLO_API_TOKEN: ENC[AES256_GCM,data:3urLCHG0KFBrUy6BT7M/wqicehlbVPyQR1h075Q1Oz+zGhCDVU+/yKAJX7Nz3mwAjhoEjZhGoNqe6TUBJZXCuw==,iv:PrGnCjzX9SqkLO2z+PtJIaYmTmWN+gugQCDILpmUP8Q=,tag:NnguYYD9EoFMea6qVuKG1w==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:/Lqk9cutprMntbwTSTo5usCD1yBqvfRubehCGnlqlvqlyTRWt/B0,iv:JOew+aDwf4WBjLJi9EjIuseWp9EjU8ntQB2y+3f5VsE=,tag:NARe9cHbzsBh1K0HFgDEqw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3OEhEdTVDemg0TlpLY1FE
            cFBZYkZRZ05tYU5HcGtYeENDcVF3K3NLSDJRCmVUV2dyNi9PTU9wUEZJR1g3cWxE
            WEFtQ0NtYmY5RHBHYUVKWHlDYUpRWUEKLS0tIEJzZ0ZpUXJ0Z21NSUlKbDRETXRM
            dDA1eG4waUJ2RnMwUlFvM0pNcjVUdHcKcDGMk3Vvc+VsqeHHxwgc3QlPGIRZCOXp
            loJ1VDfgfywQuOukuzKGQ9DMXEwzrjwCPjua2DEpechAZoqxyYXNIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yfmz6900gp85qvse6pdd53h0c698jeh7pltmhtcpgse4duncqaqq9j2k23
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T22:21:10Z"
    mac: ENC[AES256_GCM,data:r52VoIbgjtKxIPZqF3WiBSF5MzW0VshmHsDwtu/DoWovdToGHjdJ9xtAVB+Q1s4y+hw+80J5bPS/tcXPGKMCjoQ3oMQVDORBCgfhFLWnyShlwjq2dhG0buswYPAx0Q9D62j9O4xXYAabBaKXuZKkw6Xa9UbQQcugbIKhHPGn2Ww=,iv:dfiXsP7XmkxaRG/RRTLXhWlVT0phjhaypnqxziXGITQ=,tag:I+EobuBmAnan/9IRtOIGtQ==,type:str]
    version: 3.13.0
