apiVersion: v1
data:
    APP_KEY: ENC[AES256_GCM,data:P9dq52UAqtr9EJgwlQ60OiGGLgGsZxFjxNa+NB3kJI0Fr8o/4mKpwUPGg1Sf1slpxbCOltLnSj1hVTyrEoHklgqEaTg=,iv:E6MlPBXsaZS4jTuSaKlgPkYW+lS1BhfVi2HRqTd7MtU=,tag:uyR6nx6ixpjNwOVWOHRfYw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:SGWJvsgqu5JGKEwOlzORnsh6BCyC4vytPt8/tH/BGxZxKmRPxkMIIuxkuOM=,iv:zY5LFb/bilbG4fEEzMLuJ0pubRr1w3ZkfZzXM7sTPFI=,tag:2sRdMXvIBVn1Uckkkda99Q==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:phdHxEX23pyalRgjg2VCwRJmX98GrrPs,iv:Y6qw1sTqerypN1jRJIGtboSXEaMhTjNYaQwCfrFXOlk=,tag:HEnLAtr+xAlBEI0xDv94bQ==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:0zkMMo2KgKd7OpqWOXFSJC0TpdSBWAXgkGLSakMs0brU3f33Bv96U4pQhZMevYI/c1Mh85oPzPNDIvozDjArmVqMIm1uwLnLu2ae6utKkFoKZdrKfIj4hMs+r9zK3m61,iv:7ZqHGCMmw0fsBMCastcrOwssiZ/3YjBx5mzXDkklPzc=,tag:ldZFFSrpb3Vjz718X93xnw==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:OBsNF5ou33Us1XjkPiDWk3I8/uwSqioHDbCgCjKi8BWhiAJkaFXHR8zORC/YuNxn,iv:4d9tumRrBVsD0HrrPoIppoA9kE92vIAWjTgyDqd/DZI=,tag:moUA/gm+pn4nzRpIS44MSQ==,type:str]
    GOOGLE_TRANSLATE_API_KEY: ENC[AES256_GCM,data:JoHCWr/4TPfv4Byt6ns7qCirTL4sXcU6wOtH4DmTbp+Zf3G9YrQcNoUplsIPGLQIBWibVA==,iv:GE8hYBrCn/MXzboohv4KKFXLd/3PL4EXQB/C/fUXrYA=,tag:2cc8faCo7lQzbYuRIB+IBw==,type:str]
    IMAP_PASSWORD: ENC[AES256_GCM,data:YMLkefRef4ZbJLjiYsvL6h3YNx0fDuhc,iv:Sd3ceCRdyyQvtzQtaYkAptKcqfUZshjFOCQMhURL048=,tag:G6hm1VGh2UuvEYWQdOBBWA==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:Ao7EhfFA+9F4t4oCF+GYyzRUmeWwB6cf,iv:ksrD6Aqt7SNY0w/e1VN//Sk1LrBnCkkfwJ4GDSjIez8=,tag:0DmG7YW7KdXAlZJ2uekExA==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:dAhu6XAqX+lqKMsyPCZlgDTOa36XIOejvV7dnPF2bgoMpeFjMmeMznikK4x2z4+5FpQSSyxCXoHcLnLkF4MxrwBzG2Q=,iv:07Y1NTKUSUc/Xt/c42pjmwSNh3I/Vs3HmlHBbD4pw1k=,tag:9qU+etQ7+0KMCDqR27R42A==,type:str]
    TRELLO_API_KEY: ENC[AES256_GCM,data:5ppBnvpqG2l90M1S6tv4fjTpL8uNNtvlQRcpkjutcfhwe8qmZkqveQPB7RI=,iv:0KB1MvA7MhKo4HuBlUdrF6gVgsQLF4oscUFh3NxiGFU=,tag:hgIjs4a8A4oVQHyExvGArQ==,type:str]
    TRELLO_API_TOKEN: ENC[AES256_GCM,data:pFo4C4JZ0XaaGxnufo86pjioLumjtwNuH8jruvIZQ28A56OHiZrMLzoZK3KNrbZQurOplzYAvOxogBro/NQNW9aVSIUq2QefQF2+STyBSvUE01vqZUFdtw==,iv:8msM+169uZDPer3G9udPH45uaAZUN77QW8A27DT6CJw=,tag:nSmbWicNqfEKBKF3CKrVLw==,type:str]
kind: Secret
metadata:
    name: velocita
    namespace: default
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTk1QYTNLMkJSTHhUWkN3
            enNyUmtBQmMzd2szcEJjajhsdXlqa0dXdDJnCmVsWVJPZkJpbVRZVmxGMzh0bDNt
            Q09MY0Y3aXJQdzNUU1FJSitWT3J4MGsKLS0tIGpPcG00MnRvRCs3Ujkzenh2cnFN
            aDNqZlc0YUtJV3REdkpJTUpyRS9YbVUKrKlxtAVZMODIW6C8sSENEtK6JkUU0wbG
            fRtXQoycWTnAv5NK9+IfOvi6wMsHSZb2Dy0hmLzYXlsE6/5c+PNYzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yfmz6900gp85qvse6pdd53h0c698jeh7pltmhtcpgse4duncqaqq9j2k23
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-12T21:34:59Z"
    mac: ENC[AES256_GCM,data:V0YNP7xV7qF4n/e5lqCKqKbgK0AhCE1xSj8oXz9XsfP4yZK9xIXTto42/X5XECWZRidy+H15NZy65HVHTbP7UBf1gAB1MlKWSs/N1tJQD1eHYV70v2iiWGirPrMXtv3z7PsIn48EnrQJyhBvEQ1ow2xEHyhZDWM10zvbM4lYacU=,iv:NrlrFYE9wKwGCv2JpFCllP2Uc28nyqy8Q1MzaRVERF0=,tag:al9bOPkkpnJ4tpGThdYavg==,type:str]
    version: 3.13.0
