apiVersion: v1
data:
    APP_KEY: ENC[AES256_GCM,data:tcPACFUILuOx80LfZDT25hn+VjzqUDS2ct09wYmyWU7s6ZYq/1DY8mJwAZGZXAKx7xVx5+9NXMOcUq/gjv2DsmZSqIA=,iv:TAN9UCE3+o899N6e8eU8GqDAImdkXYqrTiGR5tMxZUs=,tag:D9r7Vss3r5ZdCxQB+FJ73g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:OJKuy6o15pnUaRmhZlvj6ob8lD9t6oYbna54/8gFjfMkTvc7TZXyAdn1wVc=,iv:9uHQoiXXepAOfWlZ/UZ2R/kde4BFABB8QVLXs/aA99A=,tag:6fZ279OKvtXvi7wLFOzl4g==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:WUGhiAvsF2vZXzLcVVwDhZyC0JFgTOrr,iv:dUzg6luFX3dOH0nnSBeoi+KeTqNXwqGNrieoTlWdN1A=,tag:IZqMqG6wbBwe/Bt0u74gKw==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:GQ+J4Alc5mQRwyyb9o/Q6CQiBcBoaMn9MYe8iYd5YBtP8U9f6bqMCcMyoxUOZHvb1YN+0mps6UwwOcQGNJ9SHso4w5W3PT/sxh9IF3eHcGbTh3SGfwhpD1nmWPxRFrkO,iv:Eyywh1MatRvE6ifdDvG7+sqC3gtZ58n7Oyr+nSl3iMU=,tag:fGxg6Dwa6FpIvf4q5ExW0A==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:N8GYsV4SDVisD/FV02VL5l7MdEPFslTuimEUm+su0Jp9PH2sHhz3J6rb8gWk+tdP,iv:vOqlJsPalUqddDF1KBneFXCLGJEfHwZ3IPgZcAZ/rDY=,tag:aw0gt7PrZIzSh13VurrxQA==,type:str]
    GOOGLE_TRANSLATE_API_KEY: ENC[AES256_GCM,data:kfXfnUbjnzJP0X7KzQDll5T/mpDOFKFAOgeRBfHr8muNmX8n1EQHpJhF7enLeDxt0BxDVA==,iv:JBLqBBHxnLIL8UJ9OE7KNhoe4e9oHlRmDDgUtk0Mbxw=,tag:RhycyyoosuBN2l8DY+PYhg==,type:str]
    IMAP_PASSWORD: ENC[AES256_GCM,data:VsIFC0zOUeGm5Lz2wS+YMJusUFf7bOOL,iv:dt68Bo6LcBQczFJM9VAZi385qR28w+BdvBM6ddtdZ5c=,tag:YyGN9R0TMRi6KBCcDq+y5w==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:nWUaosJ8pX2U7sq+CZy0t/gNyeBsbycO,iv:8G6GRJva/s6itNSfNP6fec7e9RgEZyWuaNs6IsbntME=,tag:xSTJc2Hr6G7OdpKb+CpRHQ==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:bG1mLIDWxQia9S5b8q6kMMDvPd7sZSF+LbBLqMkPKsv5oM/4RxnCWwO09ewqyWofA2A5bt2V3d3ZH9/D/D6UbrtcAHI=,iv:VAqqSzHpmMlWCwNq8q1k89D/tNKaE+TojdMrm4ZNwuM=,tag:OSxw2M+u4/8EEPQh4mqaMg==,type:str]
    TRELLO_API_KEY: ENC[AES256_GCM,data:dIsD8nnLhdrszxyvu02sKTyue0I8kUr7q2kGMEU7vITlIjpSB6e099A9SXI=,iv:EDW4KOJIXY4Pady6ea6hnX0Vo0lElQ815tf+Oqetvo4=,tag:IF2boJwjTjdZxLhEJKNG3g==,type:str]
    TRELLO_API_TOKEN: ENC[AES256_GCM,data:reOJXHX5boSrPYZFrDvrFGwJXZW2l6qiIL2KrbfMzxNpuo8g2CAFnHAvDqSTjNEY41rPvQpOJ3cQKioSdxXNlmkiWPxE8dCwoxJFKMk3UouazswXBA1yeQ==,iv:BV5B6sTSSVuASSHgcK13meiKC/Xw0jhO1Mf+ywp2KlM=,tag:R8ZWfHO67ORuTfB4mjnHdg==,type:str]
kind: Secret
metadata:
    name: velocita
    namespace: default
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VGlzQ2ZDZTh6TzlLSno2
            djdMMENKdGNKYWNBNTIrSU1TM0pYcW8zZkFZClVLbjlja3RZS0pQNTVJYytEVitP
            NDI0Um1BQW52Z3dMRE8vdHlRYUxldUkKLS0tIEJBS0t4VnorSkJ1L0lQa3FkZkJa
            WXAvRG5qc1ZURXRvV2IyaWhIcUtnUVUK/XPgwYKgNvaRm5xDLyt0eTvA8/6Wyruv
            ehxbhzEjtYHHW38wL/WPOhlqqpPSsMfX9gglU7LVAM0IpKBTuqXGZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yfmz6900gp85qvse6pdd53h0c698jeh7pltmhtcpgse4duncqaqq9j2k23
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-12T20:35:02Z"
    mac: ENC[AES256_GCM,data:ikZr6Z9+vKhZNAoz/zyM0MB0ZfwFQ8265V7kaL598UWdcisKJCmz5YTKwHqxfnbPmh2UPFEzGmiJEF0lZ3eDJFvjBzv5+fZrxcGWpNtbOKACN8zQhODt0bSS6fsKPeI+g8JFDYuK7RFQdueW0/SFye1SW1LpsXIJEoMvi5hV3IA=,iv:fNNiY8EQcgn/0wbl59BNtntcn81MIKpfVtoUqioWhio=,tag:NOQo4qn/RCX6h02/1zh77g==,type:str]
    version: 3.13.0
