apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: velocita
  namespace: default
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: velocita
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: velocita-horizon
  namespace: default
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: velocita-horizon
  updatePolicy:
    updateMode: "Off"
