apiVersion: v1
kind: Secret
metadata:
    labels:
        cnpg.io/reload: "true"
    name: news-alert-postgres-credentials
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:ATRCqsK4Xqs58e5cdWNP86ub,iv:Y3FNtLqIKv62ZoHgolCdsPv422cf9T9opYYkyaNUnUI=,tag:LGQAtxqJ2ilNjE3skklKZA==,type:str]
    password: ENC[AES256_GCM,data:GR7RpwPq/7ilHWwzOWuOUc6wTytTX2sixsuwuy6vbHu9pkMVezZ4IkkNfg==,iv:hCD7p9KKXgaaLcXNM3uiar3VWB75IxjEeFu68eEKUBg=,tag:YePTkgyAweFbbuW+ok11Gw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQndEUXZwamFuTVFNTFdh
            dGVmdnJYdFRkRHh4TDNUV05yMDhQMTU1SG5rCkNBU1FWajJickRodUpYWHVoeDM0
            dmQvaVllVDlHMXR4SmZVSmZGSWZ4SFEKLS0tIEthYWJBZ3lINFEzUUtoQjdqdlJn
            WEJJY2wxakV3Z2ZRSWpWL1FmeGZ6Z1kKJKvGnjTRdXGWv1sCZVirWFvEJVrKjVDl
            RDPCaa7RnZ411hHLbc6A3/mEczdVz+bN0tImt5QlBZQPGMC/hzMNzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yfmz6900gp85qvse6pdd53h0c698jeh7pltmhtcpgse4duncqaqq9j2k23
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T21:21:42Z"
    mac: ENC[AES256_GCM,data:jRR5kX9s+Yv9mb4Ahs9cwHY7fe+BM/+8wjuNe+f59/Qr7ojgq1DfOFOzWzO1VitMAupDY9kwwLHbVLlvjGJAx/uUzhl/i8lvFD1rhzz/btUS5P7wovXnSDnbkbryAxI0NKNpkLIMcmCOsXOt1Uo7A+LFmLYkYyztWK66KqNMz5M=,iv:+1NKoJ1xDSGRWSgnkd1TpVg1AnnmdMyzWNQZznSsGoI=,tag:uGj7iSArq426wM2qJrPwSA==,type:str]
    version: 3.13.3
