apiVersion: v1
kind: Secret
metadata:
    name: news-alert
    namespace: default
stringData:
    APP_KEY: ENC[AES256_GCM,data:dV918sLi0RLZqyjv878WB9LrdfoNoxBT2IoxgzDcxsk5xc6rr8XuM7oKBunXwvmGOmXb,iv:2m8K7gIKfUVJWcBwE8IgmIqVG2Kr7dYn9VXrKGZjjlg=,tag:REA9IAt0PTi4WLq7l56a6g==,type:str]
    BRANDWATCH_API_KEY: ENC[AES256_GCM,data:QIQXZzoiueVftaHoGoy8zJQ0YBBQSHEFz08xpHKr5B2oPnJsQ5tYniEN,iv:ifzHYIKl3jooB1MpFJ7I2Xwtbm4J63ffTsd6CvtIsiY=,tag:LdB2l98fPD5X7VIk1jPaSQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:XGiwBE2y+ErL+hxaCb7TO4eY/92XmeLdtpd07+V9J2KTvxoN6snTUbCddQ==,iv:QOZOGL3zABParqATgXCyZlInyyRxABrIfBE7vH+go1w=,tag:+tfbuM3LNAqSgFjDlGpqbg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:OUN+8Kntda34Ov+mA0RpP3Y7oM3/hIHZPdxqqfezohIgCs/jiBzvcu+TwjBTLXD3Eh1nmOgECVOOB8lHSSq/hlIbjSIdL8qMl/PpB71qnGp8AAKgsD2IrTLxfPwz4MiOR6raYhBpzkivt9Q/DBhdOOQ10QQ7pa4WKspQoxHIT/81e6eHLuIusd49UPpF0tszXBzz+mIoctRpOhy3CEHF4AfVYBY=,iv:a15TCFE+KiJr+3JH1tFFdleCNNWPYTDJWuivd425Dco=,tag:wLhToL3DcpeJGN+ZvfivKA==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:aO21TeGFXqKSkJdfc9D3MTpVuHOmoPARADVPwry9u8/VvHj1LJRx,iv:yrCprICnWod8b7Bu2/NOD7Zziemvm70H73d1xHixLpE=,tag:VTHTyrM8pE9bCaDeq9AF1A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VmoxRkNCeG8xOEVGb0dZ
            ZjRLdSswSVU5OGNlNGUrdFVkS05kNjNmZ2tFCjlpVDJuaHlFbFJZQXV4ajJ3ekd6
            bE5wbUk5ZTI5eCtDNitEb1VoZ01TOGsKLS0tIGNLZk4yZHFyVEorTEZkZFdUeFhj
            Znp1bkg2bkhacVRZRVBORVdSTURFcDgK2CSslxl0ZSiuh1q8NfTsEAbGSzhbW7IT
            W7cku1Q8bG7zzZdLdSpnxcmbabdIS6iOwU2hBORwTCWr50d0wkMBOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yfmz6900gp85qvse6pdd53h0c698jeh7pltmhtcpgse4duncqaqq9j2k23
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T18:06:04Z"
    mac: ENC[AES256_GCM,data:Db+z+JAGKMcJ5rII7EDWX5ydtHAkcS3pYQlwMjaUloej2Rjxg0xI1dT/fxJjgvcMmcKNPG6KBJcIwDFUx3LxyhaM1VwFjvruiC76ljfJpfuKncnDz0ZMAC8/j/WuE/Qhfou2LF6IoS4j8Eej53UqwoThwpktcanGOFRl5V7wJ5g=,iv:R/m+UYZ9Xmp9NnNQsrTk63Gwt4o8OUGhdlCaglXd6X8=,tag:WTBbBvveHoLE7Xh7UFmS+Q==,type:str]
    version: 3.13.3
