---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: news-alert
  namespace: default
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: news-alert
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: news-alert-queue
  namespace: default
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: news-alert-queue
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: news-alert-tei
  namespace: default
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: news-alert-tei
  updatePolicy:
    updateMode: "Off"
