apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plugin-barman-cloud
  namespace: cnpg-system
spec:
  interval: 30m
  dependsOn:
    - name: cnpg
  chart:
    spec:
      chart: plugin-barman-cloud
      version: "0.6.x"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
      interval: 12h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
