apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: crossplane
    namespace: default
spec:
    interval: 60m
    releaseName: crossplane
    dependsOn:
        -   name: pxc-db
    chart:
        spec:
            chart: crossplane
            sourceRef:
                kind: HelmRepository
                name: crossplane
            interval: 24h0m0s
    values:

        provider:
            packages:
                -  xpkg.upbound.io/crossplane-contrib/provider-sql:v0.14.0
