apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
  namespace: default
spec:
  interval: 60m
  releaseName: dragonfly-operator
  chart:
    spec:
      version: v1.5.0
      chart: dragonfly-operator
      sourceRef:
        kind: HelmRepository
        name: dragonflydb
      interval: 10m
  values:
    replicaCount: 1
    crds:
      keep: false
