apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pxc-operator
  namespace: default
spec:
  interval: 60m
  releaseName: pxc-operator
  chart:
    spec:
      chart: pxc-operator
      sourceRef:
        kind: HelmRepository
        name: percona
      interval: 10m

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pxc-db
  namespace: default
spec:
  interval: 60m
  releaseName: pxc-db
  dependsOn:
    - name: pxc-operator
  chart:
    spec:
      chart: pxc-db
      sourceRef:
        kind: HelmRepository
        name: percona
      interval: 10m
  values:
    unsafeFlags:
      #      tls: false
      pxcSize: true
      proxySize: true
    #      backupIfUnhealthy: false
    upgradeOptions:
      apply: Recommended
    pxc:
      size: 1
      persistence:
        size: 30Gi
        storageClass: "local-path"
      #            readinessDelaySec: 30
      configuration: |
        [mysqld]
        sort_buffer_size = 4M
        [sst]
        xbstream-opts=--decompress
        [xtrabackup]
        compress=lz4
    haproxy:
      size: 1

#    backup:
#
#      storages:
#        backblaze:
##          verifyTLS: false
#          type: s3
#          s3:
#            credentialsSecret: velocita-db-backup-s3
#            region: eu-central-003
#            endpointUrl: https://s3.eu-central-003.backblazeb2.com
#            bucket: velocita-db-backup
#
#      schedule:
#        - name: "daily-backup"
#          schedule: "0 0 * * *"
#          keep: 5
#          storageName: backblaze