apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: article-service-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path