---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-docker-pull
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBSXjHVYHuFYv/BFuqOGs/4Xd5zgToi0Ma4t1F2xr40JaRSgJccvkSVo615Q65As39tldDBJTFat5X9dJgSf+KLP5UTdx68xm8FDmXj0bAVkHRx4EDoSx8uRwgSQs78XkMIMXRnXV1W9T/GWOWXjO6B0X7gbP1EPZgARp3QIC6tX7p3+D3QwI1lJhX785p+Dz4H56QK5FiXgEKj/z9ktVW7eLNNM8AdvB53kWcg6PhwqUSLnbJYTPROfarA2C+WfR69NBQ1OpsC4vBs4KqDn6f26fAr9I04xbuWCcQIWatLCfUSKWH9HRXBjhkxZ5epOVw0QJyX4kYwvyYgSeO02TZc84D4bXSviccLABmSa93DYxpUTjv2gH7io/Qk11/G0TVLPHOE/ulxfggcU5gTf/pRO4Mq73o3/+lHB/IEJJ2jF3rEtv78Pqh4RbPBpKyiud3se5EqUZFSWn7B4FjYhXbbxMDi6cjK0WH2HJZEXyVlXpxobm9E7AKa0dfAxCH0GehjqQ7TaU6jGPiwQxw1CqfC4NHlzEKCrs7oGnPqBNsQWWTdruEWsu7D/FWsh4Rop+xOyFK2L7Ccc0uQARXJ9iUhtW55hEwHEW+LNBaEXRFwfDzRgE+2QPFckakrhJT06TGItpRjHoZHemfpAYw8KhqtjWVnjaVYCmm4gBHfof71LsxB47XClWrKrsRxyvZCNN0MelfXK6hy3/NeZGTgqUG0QdgKL9QkeYzZqz3ru+/FXeY6/wAmsEXVggL+m1TgMlLyRJZBVNZcjHQ26F9dlv9XEmE6v7gfIAACbftADoFUXp97x7CXb8VzjukSE7xfmg08gmAwu6BasgCFtmLJHMnN5ADkoF39sheHK9pNkqCt6CEJ2Vw2H3tYeumICVM57xjLNeeNFsXjSNwWaAQeAuFPkJFPPyZIuBo4pAkr+BcDmX3JTYkbLw2WRLlBaf+Pt20tBoHaZsLkIKwZ131EsML4reu4BR3tehxd7G1qPM76Rd6G1MQbS6IQindZTsuR2ZmlouPZgF8MZNbwigc2KRz85PaHy/azqEv6DZRY3gvsab0UGTQmf9eNEi15rayRTxvu1HuIBvQ1JsgjR7KQ9VoZuGkylBScZHt/p4i0o9tSAjMee4nKo2XKBnjg5uM6SMzrNyVYs3sOIojnpgMjNfVGSoP0zMdxFJpO+vVBKG742ieEuO+uEIZ/3k9N413JRqupMEFMJAwHzqcWO9VOoAR8Og==
  template:
    metadata:
      name: ghcr-docker-pull
      namespace: default
    type: kubernetes.io/dockerconfigjson
