apiVersion: v1
data:
    password: ENC[AES256_GCM,data:a7V6dOSx2a3eczMIe5BAzySGIEjdmBpycbLLVg==,iv:1SiCevfr140dXLgIcWq+fzX4Gilh7UYSoPUUGzG83eQ=,tag:B8NKh/SE1t0NqXNgmwajsQ==,type:str]
    username: ENC[AES256_GCM,data:2IEWT4MMlZgQsRIDsEvnW0MrOdcKrNuz0KgcNQ==,iv:xgYbucSiMQ66pjaGTUeRrFwx214q7W0nBs/AJxxnHqo=,tag:mpUg2vxeQRrI+clrnKJvew==,type:str]
kind: Secret
metadata:
    labels:
        cnpg.io/reload: "true"
    name: velocita-news-postgres-credentials
    namespace: default
type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMTgreW8xRVRXODNHaDUr
            UDkzKzBhdVZ1bWF1MkpyTFJuNHA3VjJtRHdJCmdmTUk0UlV2c1J1MCtFZ0o1ZUJJ
            RldTWHp5MFp4M3JQdUNYdlBoRWtacGcKLS0tIElsVTdPeGdacnZhOUJ6U1k2VFM4
            VFNkZGt4UHJyeW53NzJPMWx5d2EzcE0KT4Lvi0mjV3Ch0o72MXP98iP/ipPGwrKM
            c+yYGNJs6LphbqNpteSnvoECzCvXF3pnH12h6LMpKiAoaDlSUzapyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yfmz6900gp85qvse6pdd53h0c698jeh7pltmhtcpgse4duncqaqq9j2k23
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-12T20:35:02Z"
    mac: ENC[AES256_GCM,data:+AeoXjDSkInKL/zyb2VR73ygAjS4Z64mixbtuEy7aietQHQatW0UEVQSo+YIWMC9xo7hKtcNrfoyGqLas659NafboFPn5+n0CJWcLALnvGCq5UfNdJldccmW2GuE2N7EYjDB0GZvvj6zBRyV55Wzf9FvBshtI5pJe9fKYdlJ/7I=,iv:Ivjn9fuAHof/Vc5XgO+BZ/I2i9lRoJzbuNQUA6pDs2s=,tag:iZXKv5p2RKMmNswhf8o4hQ==,type:str]
    version: 3.13.0
