---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velocita-news-postgres-credentials
  namespace: default
spec:
  encryptedData:
    password: AgCu5pTDa+BJ9P5DztyxOHF01/G7pxRri+sg/oEyRid0HyxFIqzbUIPAH7ju+AjpkmFoVKwpnn1xv5M+JP2hkuP1SGWfq6TPTdIA9+Rs2BdFQdezeP9TsYk9KopQ+uQTCZF4Pzoip51bEGfgqpKcTIU3ZpG4UL6KKKlskYId0Xo49WiKc0f320TKryV9JKG/IW7v85f2zAqXmyE6g47ecX366wBmjDqI9Aj9jQ5rqn2pq7ySCHvH/WIzVy+6+MTSR9wNbQSk1VBcifinlqRfnNGRbu8YZch7xBxK3rCEf9LifUrqi5mlMWWhqT5xGhQjpkw+7VJmV14fgu2y+5wXQ8CcZWQH9JH6k2MHI4QbELHhpxBLYv1fcyD2zjvdcdW8Rrt8rUgcJ8sA/a5JNMvcXYvowh1SU4wzrNdQae3XdxvhpFYSGVo+JNFB6SV05E96Eui2Xoe6o/2sedM8pNecy/VlY4LjjiKNeriksUApCEyGNOHLTZfFanh8KBdS06DiKQJcaSgHiSMjzNw5AMOI1qAu1Pm1d7xLysgPCt8fduYgf7EEUNIk2Jxfzt6qbGTIGWKDW9yvU5J0wcfHK09v2h5nYQhrXg2YmVsezGr2tb/jdzAIxOyKpGhQBiCOypBDlfOpSDWbWBRDYN0jvXTVn69UK4eF41xYW44e8hXZZuyWDH6Fw3Mss08FTs/zuf94gq3/acYv5SjOydsXbBpRjuSlHm7w
    username: AgBWTbQby/L5DSeWwBKES1tOsmdQlxj+SVO0VC2tuNoTl5Xn3jG8aT0r2Dme4d+jbl4AB6QyK5094TwYaWb8aTtVU9vA4h4B+rY6heomQ8qPhmHvWmT+E59Cv1m8/xlgI7Kz2+YWzSGt5rLx2p4TBZh/Xpi8kgxaVvlQKaWwPLtR/xuWuo97/7OgvVbEneUN7VAdzfg6tV3FTBpk7xOpcqDZxaQ4n91DQChyeIMk0d4QbsCkoAB2MTJoKmrukS0Pt4O0+JUH55+6y3r0/jvy/LUVmP61Xj768kFK3CJzNegcc1yThM77Yc/V/tDO+TOxQ9Vo6mBLpDVprYaeeDdu7XD2rn6fan0uGZrhboX+0n+VEL7owNXnuNsbrlroq5lg60lM/MQWOH80jxcc3Advg6F8GTfsAP0ZJ1IHZcYauRf4V+7yAwFBoW1PJB158/ZlJku2klT0+V2f0WaH02P4Ynty//i8XzuHFLo+eH9hb/EKtwoqvWiTep75J9o7A1wiAB21YgPQfklmoX9MU4ECCTHU9d4cXY3D6ea/RjvqF6xlmQqgOaVcLEOfLy5neoJtPCD0oxyBns6KizeuyqrjuNzeQPf0Q91n0kY2pAwC1qAEooOjYcLAJhU5qy8F7SUEY7ikyC4vi3vS1BuPK3RCvWA0v/OanVc8lCtR4Sf/KwJ0V+mPgFmO6ehHCTY2ltrRpycsQLyCCGSw4Zval/Ahj2c1XRuN8uo=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: velocita-news-postgres-credentials
      namespace: default
    type: kubernetes.io/basic-auth
