---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velocita-news-postgres-credentials
  namespace: default
spec:
  encryptedData:
    password: AgBNS/CiM/pAChyfmaJee/KLkPeyWOxhK2/0c66I7ce+MuxMBI0sNa9ateMW2Y+EBxyIxYKs5yaU+t54biZ64WmhIAO2aPMZav44p4zg/6j8kWTuohzE9+pWEBVnkKT4TRvMLAED72ZXbwbqKAAfPRwRJNUZ2aU7bVKv04gz4f+3+Kiv8nzDCf1Jxmuzt2DSo6+v/tWA07qeESeXPqoQ+wSfYrkLQYqLoQMbjdjZtjMzwD84udYHEEc1nMZj9UKf5gkRh4xQWRKpXuv+/PBylVOtcBWOxUZKUAbVHj9xG7fiH+U65gSMjDo8XrKcjwQ6q8bEJgIxnCVDLbYiqIA7OLJywzwfIyo/Hp+sznUNPeVz4RCaycuJt8rn0wLxKmIm0cVMdmctl2udEEYYi4+f/2Iqe252YfnUdZ8ul72qQuAK6ou9phoDzMyxfE2esLOhyUu+ejHxDNNwmxV5aNCdvr7YZfAs5IePfI7EXYP4DwlpIruYl1In/PBw87sEfz4I/sjSHvMZSkAQ8DcxEhTpp9Gb5XgkKTsAt8dFY/ydpX4zSIMf8ABarXD6MaVMA/E8gvjtCltR9yAOklCKSZYsVgMx6V2dW7NtvMCQXcsmxNPUdAP3/gOyEXfuikVSFqxc6IhrW9Jd/18XoUHF5FazuaCbaayOGztL2AqbHRNYki2C665wqiXfwgUmvgBllu0GUTe2jJQm7/1Ru1dfKrZuwnOCYZpy
    username: AgCEfbT5Bs2Qtvuz7vHHzcWIKaSvy7r/XjQ+lnQZh8/74FNtJ+1ID7IP3C2FJcd/zSRlTFNTYT++M09EIxn2VpBXN61EXVr/Fp+ZnDB8atcDOHC98NpUX7Y10pkaX9W2kPmNPixv3zJJF6pJ9evqJ3KtCFXCPnv2XA18Y6gZEQ6VOdHzqy2Xm8VnHAyrPxUEJDNC8pdNJexROkcp/NjNYAaQISPtzdl4u0BFFjXhG3HSObv3Eo9QQQMXyN2a4sbHy0zlREq2pc7OCnQd0yqqmRTUcy7XLawvezZlYdzEuaOOOHhM0mx892YRU1N0qoLdOgfW+BN48Wm+cLbpiKUGO0NiskkUx4LJlyajY/hCyWcICsDieBtIZc7NZxhK75dpa/v3KyxyoQ2sKgWJEszFZrxnf57WHrSvKhRT2wZc+voNwJFGnF9/EiBpThrj3frhw0IuiDpPfxsA1It4Ua82mQisrVt8c4GmNNAulvd4f2HhLb+09+WyrSbWFT/21th0R30XAO6EI/j9vlrdYhHUdu9ZsYt9X30/rAG0fv0kY5WPKV51A+gPYP74X5gsG3ATaownRvPBsMO+T61vS097xR8zq5i3Dnc8zhFK6CO5PnZZlDn8bQ/oLnxpcyHKXkxpkRC53vclFERDq/9uQ+Q35v+ExaQG+BbTlNgsQxDVJ7bI+zFz6iEGJNcfVjVTjQMzyCV9nGcEoD5u3+MvYdiR9KJpqunlY0U=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: velocita-news-postgres-credentials
      namespace: default
    type: kubernetes.io/basic-auth
