---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velocita-news-postgres-credentials
  namespace: default
spec:
  encryptedData:
    password: AgAY+w5Iv0UDqxym8xtTYpktE9rZBL/U46Jf57JUfaywudMPc7fUDWb79jVI3y0cnETQxCyviskZnKgLgJ6oOSiltfZZj+kaUcUo8BcN1red7BqP+4Aw+rtsmDWtNP7nJQYL6qj32py4DT9bhXZ9bgBqZYGBME9w0Wi3pm9LD1lNIrtC8Q34gOUDOUOGuKNIw/YASsArNtN/OXJqv4nfPpyY9vQK5XNTwYBHRi/2XremGx75IfzhMEVVlRkKXf26EG8wsACZ3Hh73TzOqSPNUEWNkQM4ml7SHIXW6mGN7JNjxPeMUZqidQsXR1FAQ1tbTSS5OQms6vnR8j5ITt/v0EGzGJySkpSIydwICce0+qZeY+sDvGCAgGav1Ncq5atRCUSoumI5CJvMKWknXmftgAFvFX4SW7QbT1IWelN1MrS8dz3P9SRgKPqkWenvoV/AARJ9UwLGarBciS0nx2Ua+g2XPBdnMqjrnR+iQU6FVOiua1Jf6KhXcssMJlS5209iIuo59YVdTSMIB95nAGldKWINP+M4tlzLLbfrlgivOWsz7J3csLK6Ck3nXFQouzXuKx/zCSZoFaMNvYebHbDWpOGe9qCgD/yh6KfbYY5KM5mQ9KybeK1QGiZVAgaQoY9mnTZEo9rnSjIot11iIienggvW+fOxfTBZi95mOh/q3zWtNnD4ncblUhipY686kXWfs7osDldUm6jPqFBBZj4Uv/b5A7+/
    username: AgCAlk3/LEnCIQm8yIYc2KRK669FnySPkHZMgpVeRUPmq8spxCSkpMovjk5uNUFNSgSAtf3BxiZq1qZupSNVQK/pL60x/wGmk70YkuMJZ1DRg6Ar24t8eB51XJQSs0UlYdBJQXDKciDhi+i1BGIbzHYMeqL1VV/4uTqqPy2yhEwjr1FuCzYyxPUGWW2Wn3rJ2MRmpd4FGnsbDw/YMk3zGAjCU9YjqpXIsVR8eWvW2n0PdKoMKlp7sDxrjqpt3sc1j2BpkZKbHqm522XK0vtesWmhi/Y/U6eegXpFh/pCcrOJWB3/TuIaeMcDnfcPdHGg7ul0sX0SSdr6t4JzFhTdQb0Tm5TGLsFl1ylZXfQ2vOPAGY8QRCcjDuUg32Uiih4N5CIhwZcmhm3RJycmZj4Mwdl4eitjHmLlsjRg9OHjL1HvFvmtbrbhocDHIOYh+sHqFgHQC+DdWPlas6odLrfF7o2KrIy3OaaI4Tpdx5JJskTf3VZwjr8Uzrg7gloxxGuSpzcAFLG+DuIF3EX52SPPvAMbkuapvFeu0b+pgbemxzdiCutIYyhWsGVrnfn6LY9I/iJkss5Uz7sqWuvq34ay/ZPjSoTOmYFAqAW8X47+X4OODyRt0j5rVGhHMC+Wav6JJiMoA5SnHT6LHKFyFboyT+EU9mmVowZm9N9hC3W8cOvQPjpRFG3ijmFzkgCFoo5bbV0JjqPmj0F4pE8YP0ea+D5QMqUJrr4=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: velocita-news-postgres-credentials
      namespace: default
    type: kubernetes.io/basic-auth
