apiVersion: v1
kind: Secret
metadata:
    labels:
        cnpg.io/reload: "true"
    name: velocita-news-postgres-credentials
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    password: ENC[AES256_GCM,data:En/l59S1asqxQn6O+hB2RNtEaQ==,iv:N20SLURXjPvnqjIDzF0K0+F3Z0JZAbsROlHKbnAktBE=,tag:cJz3SbkJZ/wnsgzjFiZg2A==,type:str]
    username: ENC[AES256_GCM,data:GTymYteZxSwSoWBA1y477PXxboue,iv:6zLURwL4LLWXidr1TOD9Ap0+riyDoJzpLk+1WVpB+JY=,tag:JUNDyczNMwXj+uRlZ8hzsw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByY3hwb1RQSE8rbFlTZ0E0
            eVJGck9Va1V4MjdyRXVQeGs2eGtKS203MjJFCmw3M1hUNDcrbGZYdVM2TW13MzF5
            TEp3RVZPdkVoMlBlL1EwSHpPMTlaK00KLS0tIHZENXVKU2NhTS85MVZkR1BoazV6
            QUQxRVNyQlp3TElCMCtvTVl5VXFaWTgKODbzHj9nZDrCLmzkkUkHAa7cf1ElsTSV
            EQC9Qga6RQtjjs+EQc6JH53couiPJclGNVXqoNIJCD9LGh7MEvkfBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yfmz6900gp85qvse6pdd53h0c698jeh7pltmhtcpgse4duncqaqq9j2k23
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T12:11:08Z"
    mac: ENC[AES256_GCM,data:5akWvwOJHdYlUNxCywo+nuYasMzNzdq6kha+AWH6Bmdt2UY+5Yqt+LUNaNnvtv5d2P+hyauPSpwbFJWcRE2trC3xjEShtP2e+tIKUbRg+7dcrzqmiaN4KZmeD61fdbLsp+UoPZ4YKyWd1gCGvjnY6w8r5xlDaJfGyLZnV41TmMw=,iv:6na+ZjYh1iV4mPKpmsE6Q9ij6QDg/9ElOoMT4kpmWSQ=,tag:fIhoTUroqtQuSCx0R6QtCw==,type:str]
    version: 3.13.0
