---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velocita-news
  namespace: default
spec:
  encryptedData:
    APP_KEY: AgA1Szy9D73lmmM+FeMhx2sFRZApBWWOPY9wYT3JtppD4UB+W+vYGJ28gOtHhLk30rWluTZpAkw2EvN9hp3IadfR2wrEDmAltQmEAjvmQX7Zm2HoTlZwVKUugpAkk9295xny7IxqsVa/fzwSPa8jaCvLJOEdbrlgZYoiJnHAaU1EXrmXsZnzu4VDdej4g7kE4Xtz0NUAFeGJTmEOJKRcUnx/Xs2QvECV5gPOY+ntXAi+uYO1iW/H3gt08EErZ6A2pA/NrKoJQK0tr2nEVIXhqbrAXVPo2uQ3AxYxjsoDXDLEjeDq71TrYhayYfLd1mh1xKEW19o5rEZPteAQ+vUS4B58kAGc2Z/sqC4OpL+CFDxWSgBIz/mULVvLXP9h3K/t7ZT5O4YCnWpEOqHCzlVUTREOG1EwPgQwKyIgSshR7ay7+E4S+hr1Uzz2NpIh4637bj89hE0iq4fu1lsP+Y3fe6a44R03450Bhvr+yyURxIF53kwVztN6W7UBCabuxgZ1Si0hEdVqW3iXcE22pmos4ViVbchQe8oLzqXsomF/SghTguzPy/llLRNXuU7H1BJBxFnY6SYvDk/48pTbDjA5m0/kFrIIfvnKXKEu57s4mDIWz0YRdw/Mpl6pOgHiT4xuxbrFujrI/+WUsPoNxH/z1IaXEwJEkiJAwXyeNFE0/fJM2JUlNBy9ooO+pMq3d3Q0EVEHH32aEdra53Pvf7fsYiTtDHAIOQEbjEsJm6kJioM3vEOYTiMvJj5aewJgFCFKq3i6RmE=
    DB_PASSWORD: AgC0UUfBa7yXVHZ4MjWSQk+PUPTjIpQ+Nbk36V/DuLvwnxaBS4NVfiqSgzVoOf7AXtXQW+eBZT47hMlDPqYWql5aLA6+CmRA2Y9vgZHQRH9Xf2cK4HXm4cS3lwMS5SHEP2ab45wJwDdX0UE0j0/wIkPp0tC3+PYPmDop7lN8eN5J/mnyZa4OKsr7C1ObrI2zWAIZlY6uDvsviNkgLxBLbdbO8OpsJarzW0fCaJbVFd86CD9wmRxYMY6doZsFa4lhi2ZE267GRMor1P+caSH8zI7NsJ4pUIV5qGE61BpPhOZ24JF13C6jbKtXtANi44mzWsPJQamlD8gn3+82578rSOSel1uTJPyx7d4s3y47V22n4oazrg5i9O46mKLAEhSih3BGpos0q1p2i07vR2dWRfQL0Bynatkd8bOHZom+I6xyI0UylD9X98TvGrmq4OHwkldwE8mAiWVYzfDXrVvSQeWwP0mg+LGVf0Ul51MlfgaR1DtFilgp76lwvX5nyfHcPSKSsbzcB4onIAvjMW55nCKePKeApt31Y6+5GvXke6A4a/HLY/aPKjjGFkWP/5vmf7s1e2ewEKzwVIhJntoG4WPZEMByC+qjJB+snmSEJvwCV+8758y/Ikm7KDXp7iaiePJhdxZIWFidU10ghygyqvyn1hdZ6p1bwSSe+osT9fiWcVMe4N7uoLR2huqrOcGPK9oSYqTHG+ye3k5KDJbEvq05tIUa
  template:
    metadata:
      name: velocita-news
      namespace: default
