---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velocita-news
  namespace: default
spec:
  encryptedData:
    APP_KEY: AgBZvgB2C+6ObE2mRcL0p/rTn42vzXeFE7u+x2Gozn/2aUmywAFHhtfp+qVEfJVWRVaUf0wpA64pO5LmVUGD9LZFRgv53hC9nVY9kDjwNbJ9bbWdClONb9ArV2CuNfv0R8SUSNRtXyMW8XQraqZ9ZMXqqvG6/F78nGgcxE6AV/eOn/RYM2liELvO9hzQabaYRTLghikgJdQhMIuwp+bArCZMvwA0S3v0CMgsQ5HyCEJR/sS9yGT1fjMkEgqXNULjcwDKLqhZ4pwON/hEgHBy6566nyX5OYp84+deIVy/HdE7LTekqDB6BuvxemU+z/cDwhb0PYcOnk2zGWqI78XbvCnIkI6gMFqaI1Sqnzuh5CctWCprg23YV4niFwcXdbDuNbdTtjQDmbRu3ziqYwvZ1O0CzCx7wbW2ZRkR/U4QHBkZqzgcS8f2QD3MwOmlWOzXkhsnGb7BTchCN2eE2KN/HiGVIf9mR1I6mumOr1xn3zJrS8vchskuyYYtomH5h82lHi150/f4eu2ZZMcMVZK4V/jrDhd08+PAUOLPb5BCCPDALeO5aWrAI788sD2JY5PEHz3Gb3qURRfLB/zYvKXv1u1nZtyC7zIwMcWCSvhN0OcT0FKwdn5kQePCpBl4tIgpGsYLxWSatAtqkKcC+ahqCnZVqd3dYaBUJpJ5/w4auJJJSxjI3TehkzY5RwwaD55loBDE1FU4JY5XnTy21lm0fUWU7GO82z9cwe0Gxxz/8YduTon74WRm7hGDUBUkC7WrXXcHInQ=
    DB_PASSWORD: AgCiZf6XW9TktAwKyLaZYPbzjk/5rEtN3uMLAQzsa3VtIpFObu5fFi4GDJl+bVoW42Q3d8sS1QLYQuS+blDKBFZQWylzfrl1obQOp9iUaB0CDOiEGf2V+D5EmnXK2URTzWVjXaaczdcvJr+r+4vZ3BsEHkm2hsoRNGz31r0KwzgmC+HON5ILHzE1QBksBzCaPp1wgs4leV9B0WRW8ZTozjpc6TOCDTIax6PgeLqbRdQn0W0z0S2ZMVpLLAMrHUDt1TIR9Uh94ONyA0iFDqcAjNseX5SwpC/VlHD2id5+hLu7SWRq4EJNUZ1Zx0PF+/4h2re2NEPVSahPiqF81V78RR0JJ3te8VYa4zkYGQlVWwK3e+058Qr89LG/zfSb9b5EMjGEAEq6CQu3vqGQv8ndR1In7Fxja5rjN5o1gins+4P4O5gknYKWXDp/3lr7AY2Ui0GRbBb0YLovRY3Yt0HhLOPGIyLAyu91J9t0gsCJtGj8CFMYssfGh+CwgqFWdKrY5Q3LNTLjLEvCHXBi4WTtr1X5vZs5Cu5CYoMY2gbn2L7+N3PjT1tPNA6rts7uU25kOnd+IfyUGw7bUDUo+d0+KfdfHMp8v5QkYzJHHi4iPf9OQv73h/cJ+ZGt49VstodvmMkCOsWffM+MgEAAcDvhpWNSi5tkyVTFZM24TuVBH22Jx3B7Kkl8cCmx58zI33TGaVUB3s9sclljtiHclW1TL27I4CsR
  template:
    metadata:
      name: velocita-news
      namespace: default
