apiVersion: v1
data:
    APP_KEY: ENC[AES256_GCM,data:KvRuc99QTh3DX4ReSSD17FxQlJ7Y3GmyBsK63IkfKuIJ/H6trHHEuXPdob/RCQHNaeqM4m7negicGfOE8EfIbJsIAHU=,iv:oTo4nEu++jdNn2zyB7oR7aPCpltQvPRrNhUbWt1WxqM=,tag:vNSOCHKiVfjX1W+zZqYDoA==,type:str]
    BRANDWATCH_API_KEY: ENC[AES256_GCM,data:+24lO1qbXlT19sFJBE8miuQZq9EMKQk+Wu3q+YB82jIREh4S0szs4WNlcDB//PKUoTSU2C2ikvE=,iv:N1FXQBYSCAoI6kqY8y/PxcUXusfJ7FXR+zqXhkGDsTo=,tag:KOybfe90Bpcuo1lobEbP6Q==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:hcen1bgr7OYQezWI0H7iA27bcKqwwR3ZhTNDCA==,iv:Us4wouJXUDDVXk9GgoG4N6UyPg26noWLVxe+hyEoRnc=,tag:vbpWBJGgO22hHMdBlTcKtQ==,type:str]
kind: Secret
metadata:
    name: velocita-news
    namespace: default
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmaDhjUEREdjl1Tk1oOVll
            UTZtdHNQZWM4MVBoM3RBTG9aV05FQkNGY3k4Cng1U2srUHF3WEtSS09TeGl5K3dj
            a2RYVG9UcXhDQlRUWkZJSEY2YVhjRVEKLS0tIC83RGorOEFEL0t0bTZWTmltb3Qv
            QUNtdHBac2hYUkE1QXVQc1BydHJDeUUKzj9YXARK9AuR9Wa1RUbg1vmJDjC2vgjs
            HmRVMRjo8p+t5OGtOBJZxezvWtAwuirMYV15/Xf7+yxZLp4+mqTVmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yfmz6900gp85qvse6pdd53h0c698jeh7pltmhtcpgse4duncqaqq9j2k23
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-12T20:35:02Z"
    mac: ENC[AES256_GCM,data:9UCv4myuSbkChkOZ/t2xHU0wKsvMfHPsR9y9LhLxsnWhC15AR7DXoMMQtiS+yYacTuGCxR9YzqDn9JPNWyeMAAzHfLkCWaHGQs8oECziEBZ/T6KoO9mtGMr4+xUK4/VWsdgBqQEv2qR+eVXmxEMBTDT866S52ftVphmxCbrcEf0=,iv:o0xXMza2YDs9dMCsUtKRonYM0Cs7ixH8jMF0FwXoFII=,tag:BiArnv70/VxYTfBpYDU7Ug==,type:str]
    version: 3.13.0
