apiVersion: v1
kind: Secret
metadata:
    name: velocita-news
    namespace: default
stringData:
    APP_KEY: ENC[AES256_GCM,data:KEqGw066bYMQlk9cgIM7OEEgZ8wcA+pXWM28wmh481moNZeBiWsTPAkskdefJMmjkqwR,iv:UJ3FREuYUqkbl+QVRJStKTJtseCEx6pweIKNn2mBT+4=,tag:S+Ojdw6zXWhfOsr74Bt/7Q==,type:str]
    BRANDWATCH_API_KEY: ENC[AES256_GCM,data:lqRhEaVap+nvvvI/ra+p6q/GUF5kBbfF3plevWHs66Af9Xo7rOR314Ud,iv:ZEmTjOfgEl5q7h+WqJsS/9IHrfQSIQaIy3mC8iZXHiE=,tag:HGjggugJXA5qRQ3FcZ8Sow==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:NZx6uLI/RF1JWKw//YMqyhLDcA==,iv:fhWURIlbnTBzv4oPtBbaF2A7YUx8kiZH+7XMiohCNpo=,tag:6f4FH3EksGsk4HxFA8x3uQ==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:5k6al1OpdbLOvGVkYpvwTMx0EOauQdB1x6+s+ITdK9bsxlm9MxQD,iv:u9dycujaULVTE0nx4QGsG5DhUqW9iy++4xXnJnzvhQE=,tag:VCuHL1TfaS8/ILwOr7PavA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Q3p6UUZIWTRMOEFwcWpG
            d0RXQTNjWG9TK1JhSzBSMmNzSDNMaGxubVVBCjhJdEFoeTFvdXEyS285SWFabFkr
            cElPMGFXM24xOEtZaVl3SlQ4VHVVUTAKLS0tIHI3QkNsWkJjZUZJWkozOXNsTWNL
            OXdpTWVLcG0xN0owVUI4Ky9TVForVzQKa8jaFRyGUvt2LBC47BlgRaG6z673d1ve
            u5rdDWDGQAoIIb1jb5EaJ5t1ORdYnLEzUl6ZMhI/uIgSLrOl/6ErEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yfmz6900gp85qvse6pdd53h0c698jeh7pltmhtcpgse4duncqaqq9j2k23
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T09:43:57Z"
    mac: ENC[AES256_GCM,data:FJKbXJftJgnZhOSAgH87THAVbA1Sm9y18M9ByWnWCxXR6iLuL9yqmM2/zFagGk87hlLFrFPE37MFNjVVd958Xyb3wtsVEkwZjM0iBaApt4cPxeyLksY6HVBua2OwKDbvv00DDwWkd5QRFkwAcsJBbt1ctGDFj9hHsFhHGKXwmLY=,iv:CBWFLvEXyZbj5BABVTaTfvPrIcmlPo8cjp39ql4X818=,tag:UFQCLm1Y/iQH20tZXppAkQ==,type:str]
    version: 3.13.0
