---
apiVersion: v1
kind: ConfigMap
metadata:
  name: brandwatch
  namespace: default
  labels:
    app.kubernetes.io/name: brandwatch
data:
  APP_DEBUG: "true"
  APP_NAME: "Brandwatch"
  APP_URL: "https://brandwatch.velocita.lt"
  CACHE_DRIVER: "redis"
  DB_CONNECTION: "pgsql"
  DB_DATABASE: "brandwatch-db"
  DB_HOST: "postgres-rw.default"
  DB_PORT: "5432"
  DB_USERNAME: "brandwatch-db-user"
  MAIL_ENCRYPTION: "tls"
  MAIL_FROM_ADDRESS: "info@velocita.lt"
  MAIL_FROM_NAME: "Brandwatch"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_MAILER: "smtp"
  MAIL_PORT: "587"
  MAIL_USERNAME: "linas@velocita.lt"
  MEILISEARCH_HOST: "http://meilisearch:7700"
  QUEUE_CONNECTION: "redis"
  REDIS_HOST: "dragonfly.default"
  REDIS_PORT: "6379"
  SCOUT_DRIVER: "meilisearch"
  SCOUT_QUEUE: "true"
  SESSION_DRIVER: "database"
  SESSION_LIFETIME: "120"
  SSL_MODE: "off"
  PHP_OPCACHE_ENABLE: "1"
  CRAWLER_USER_AGENT: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
