apiVersion: v1
kind: ConfigMap
metadata:
  name: brandwatch-pgloader
  namespace: default
data:
  brandwatch.load: |
    LOAD DATABASE
         FROM mysql://brandwatch-db-user@pxc-db-haproxy.default:3306/brandwatch-db?useSSL=false
         INTO postgresql://brandwatch-db-user@postgres-rw.default:5432/brandwatch-db

     WITH include drop, create tables, create indexes, reset sequences,
          foreign keys, downcase identifiers, uniquify index names,
          workers = 4, concurrency = 2,
          batch rows = 5000,
          prefetch rows = 5000,
          batch size = 128MB

      SET PostgreSQL PARAMETERS
          maintenance_work_mem to '128MB',
          work_mem to '16MB'

      SET MySQL PARAMETERS
          net_read_timeout = '120',
          net_write_timeout = '120'

     ALTER TABLE NAMES MATCHING ~/./ SET SCHEMA 'public'

     AFTER LOAD DO
       $$ analyze; $$;
