---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: brandwatch-postgres-credentials
  namespace: default
spec:
  encryptedData:
    password: AgAKs2VC7TKM0RSlGumZ/7KKulOQDYoCiaBT3l2vp4coDih568xxaye5ZVBKGHmi+oC0zYwyj0VDvl16ilJPDPrxbDp8EJqkbm9HyducpYF55Yzm/N6OmD4ywJObu9an/JaOMNq+udwGKo8LFFdacMHZlX+G54+5346yuNH/hV9erUvJIwwOk1q5H+++LEhjtUPex8HABm3XrXacHSQsu4VhdWeCEvBy1lV3ZoDBFFGjBqhDM6GCFY9UjfUtW2BziYqAAnRuyAc3F1Ut/tVIFAuxqDKwtoT46pswXFRwNAl4vrzp2E0G1/GgZkOZ8pU5/vbYqERTWD1/AL4z3jZbqWEidaefQE4kzw2fIOoF+SWO/FrYBTODyvXyv/JIl4zrmjoNwb6zHfbwwRXglkK8iJMhuNKN8LnbWKSxcmFuN7KYLfikT8OM9k1X8WK6yL6+0p1sOuSOv2LK+xXvcnCFuhG/gO/DSMw5COjkp92y5EfHjg/U2EIFHwmOqSIX+aZ2BOasYZ5VY18roigny9qXHejNAipp5Vrc1Vj8Tf3Ix8+Ca8YCvJJ3hnpdCBQ6PVZImhkZog9/JJJXTP9GTk3DMovfNO7eLWH/N9wRk5u9/7bEY3dcHKzzDSpfru7r/D64AGiE7pBkhUpprR0MdwN2JuhciW6ZjfxlCCdbjj7yPtkfL2j40wkVWk4ruuQBiNnB3S5NrQ7ep8NqGwvM1KD1b07i
    username: AgA7Qvv9pjQsTdADmOgSJqsUvgdjsVHwMOTI8DTZyq1uoZxYtQvVMbomPYiV756jeHmLUWyVDH/KkvVTKlzrOvGI7iIEVG7sz2icQCBMpzIlmeXShnoeTVCKC7anE4rmjdImZFxriz9d1sK5kIyLqbhYq/mmmRZCYBTPvLzXJtaZ/cGezA9fG9Wp4+8Yl72qeJVAMpknyJdL+mD3ghTa0GqiYxKLCkmJPaq9iEeJ5RSmV7+Q1KtHLLNnfKBj4KvmEBkFfAD9FGUnakZNgFsIZMDbU92RJ/uET//0pw7UR/IU+Upbu27p1h8U/eUif8z58iNgTbMxb2XyknmsHBdxEEdCIhmZZbZgX1QtQ7/431WS7dDT4np+SgJ8XiuDajlSyQSrBypxS6ztPFBymJn4ndw/qRp+RLQSIUwKiS/9xaqDN0V6dDDJKj2cQKf3VFmO181fqjhUqf0eT2+kT1RzZTj/G3U5H//hmI0SRtt/2y5uiXAIEGmG609Y7XVVLSKTwSCFs0+2zYll710d11uFBS0kPfYG40zYCbixDRYPiRlw5/osPC/9lXGlSClhuqbm27og5J8KSycr4IderddDXNLfnbgSVXwcrJZwU2f+J7947NAvTwOTUNQJP6cEUjSwo58cyNOi6y/QGYDzNgc9IOW7oELSAxhzBqUOYSd/bFq9ih0s5uZd+ia43m1YFUmXEKcpYGjmF+afuoTFQpTjht8iZw8=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: brandwatch-postgres-credentials
      namespace: default
    type: kubernetes.io/basic-auth
