---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: brandwatch-postgres-credentials
  namespace: default
spec:
  encryptedData:
    password: AgAA/bg7IQ7DX1B25mjz+3KL+nvGC70wSn6I2QfidEIwpk1vkGPWsGuEu6nC6O5YnsQ+dNs105sCL5odvO0FBugwVHaE4eXg8CwrIA3qSzKge4EnislyHaUI0DYdsVfM0mV9U5IhVXxHgBsgIDYOA1IG5sJHLc0jIEbATn5qPkyz3MYrnVB00djZsvnORDoYjhxWObnJtA9NzlcNiraf+V3L+eHzhxtXgkWY8yFBJqR97iPlBOUqUkWQ2QD+L3JcaJAIlPgdXXdogU4twJwA+DSfja6VRDDyvxL7M3Y7N1pod7NnFe+5JP2uXuvMyJBIoFNc5uPiQ9aZOz1B00g02BMskUx1Qm7MmKk4zxlP+rkDbRNxK0liUx+WXkq20h19MQy7WnGJ2JjeyMPGmxCGCa1DVKcRbLgR5bTOcl+iwgIgp5K0xXTW0NSx6sEMFy4gBzjSAknjBjRrUXkRyd+Rk/pWE+Vr9nlWVtpmgocwMtNs8GcOJD7x6NbQZBVKqeZKb34dZ6GO5QfZ9Ejwn8u8TzLYSxC7Y+VF9qGAEWCTDPzxA8d2UmJtD4bUOgBH0MnYW/WmJKZROBxhKNKuglvw/3t3ReS6xlOwvXJXcLviqClo7dcOX7GObc2scz7tsckt+UoshI1DI/TvnjOjfbkUiZMyfxitDcUC6B9MLjgBMutwiPDrG9hFiBVtlR9+7e8JSCmFRf56VKem5ek0BEb8tFXk
    username: AgB7U8C9bYp9JD9CMLEa9BtW168d1bYXQU2DJR++Wd+rylqogGWbaI70Kumxb3s+K7sojCpqrM1IHfAjOvvU4apeGveZwqciSgULl6+Ma2mDqgGr9gyTZv/PROrw6epCWne7BRng+eShSdjYt2bdg7Da7JXSHib0wD5rZ6KAWhK8PV8qoK30AhJn98wTl7KlKfrSiSRI4LkOuGM18CM8MQX+yPOL7/+AkzU8rZ7juYeHLEB7VTyMwJeX2cyQNW6EWS2+rSG1KBYuVRPEfXQqFsXuwEKFGWsniLi4O5w7OX93yZ/xc2nyGdapM5LqAZ2P7Vfe6SWR7qCVUDnobA9sCeZ/fUwpivhzNYHyH6gMGvPqZoEDOPyVP++d4oPAUVI0ckJe/+zLUhZj0MyT1e4VOh1fWXKjlUxz8t2n4W6khySjS95yejtmubPOIrQbfs+AaNFn3IMB4lKE74PZFoLGStx2Vk2lovDmCvrVbsSJmfLg+QWaSzvjaNQOzUl/asov4685mZCAfC/LHgoesXMqmg9Vus/lyyJZBdLJ+ov0dbcKRmmjxra+qwBrAj9If3ihpdO7TlLnnmarzzTXnwoqtisJwxCH5XoX2sBun2vCtVLOvFt5Cc87dTR3PAUjRuPj/bNAtRlNVla5wyOYTAnUrjPtfZux/WXbEUJsp6j9/Vj59jkjG+b2nOZgFZmQqF/H2kEeq9bj0g2PXuX0dzIbLxys/0c=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: brandwatch-postgres-credentials
      namespace: default
    type: kubernetes.io/basic-auth
