apiVersion: v1
kind: Secret
metadata:
    labels:
        cnpg.io/reload: "true"
    name: brandwatch-postgres-credentials
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    password: ENC[AES256_GCM,data:fjK+vZk6WA9jQy4NYDcNqQ==,iv:pLv3LfsCQQCpccdGNL0ifkntWxH9U0VoZo9O/ukoDto=,tag:zgjTLXvQWJFcHrI/DGPkuQ==,type:str]
    username: ENC[AES256_GCM,data:wK7qYy/s00aZb2QX+3q971kA,iv:HjVAwI4QvkLLGKpTkl7+zUSDO+rUH5u9jRlPFnOCKkg=,tag:WaCnRpJUgecYGp6I+ImYIA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcXF5cFg5TU84MEk0QzE1
            TmwzZEg1TU02bVNJeW15WjdSSFFwVmordlRBCkIxM3hyZ0pwd2NLc0tsK29IR1NR
            bTRKSEo2c1IrczdjVzA2cWovMkFyTUkKLS0tIFBrS00ydjU1aTJGWTFGUnpXYlI5
            amxNWEhVeGFENWdWeExjR1kyYmxUamMKZXSXBYyCvVK6ozRxgT2ZoJJ8TejxFtK8
            FYcewT4IRBCI77No832eBvVv9/rSOMCHK51dG7MJJKIP32QFIMwJSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yfmz6900gp85qvse6pdd53h0c698jeh7pltmhtcpgse4duncqaqq9j2k23
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T12:11:08Z"
    mac: ENC[AES256_GCM,data:qbGTaz7n9M69lzf0jdgn18h5jnyRLQxc9bNfCb8mKFRpjaJmj15CnVjC1UhWBWu3/t/Lf+28IdrZzxSYeKlmbc4wiorC1XKjc7JRz8A4WGpPj9VXeuJWdrE3NX8aq25eMGp0Qp4dGcgRJ40aM7NKNSAPtn3KY71JwSLskqMKZyg=,iv:i5tSwoSJ0p60ojnBNJ6iItzKC/VFOjpxz/wrPsTYD84=,tag:kkZo1TpAl/e3jgvhl/Pk4Q==,type:str]
    version: 3.13.0
