apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: brandwatch-db
  namespace: default
spec:
  name: brandwatch-db
  owner: brandwatch-db-user
  databaseReclaimPolicy: retain
  cluster:
    name: postgres
  schemas:
    - name: public
      owner: brandwatch-db-user
