---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: brandwatch-postgres-credentials
  namespace: default
spec:
  encryptedData:
    password: AgBNJXzb8nK3Oq60AI6RNlFCCyBEFI3DXb3DjTEq4/uYvUrP1hDvJNYsQ4ySqAWAQiTudwuPFIFfWISK2gFr6L3zL7/ph3nAc5FTlT7WnuRuKBp1jwm6bNZztDNEHop1ZONgcCSWVrZiQmWL16H+N2yOi7jPfTtNmQ9QayPmgZZnesZAugdBBwOy+DS/VS3zRYv1hC8acMlo6CH2ZOOv107SLL4w/HJ/2dV8c31E9ILSs6bqVeeP18Y5N3cTVu/K7NiOrxtQHp/D81jzsFAoXRdw4OVhcCoys6T6RQZGaSJwR2XUOi/jma91EwXgnBHqd9R+FOWkqIYoMFsDV+gz0hWzwP+T65JO00Lfwp/mA8M/nRfMYjFd7/ggo5cCYPwPKUKw2+qyHDPY5lQNSWfv4bKpXC5CvasOutIMoFPf2aLyOF1ck3cnHI+BQC/q5Q0c4+cqI7hdmRdpNpY2EbEAynYoYE3B4w8LThCcP76DxHLSuwRIHPz3Lnema+NU+tFGQIIPu2P8UPMlEelgLhZSXNKJRTL2bzxhI/xSM1kP1SMk+NuATBkfSh/eHWsDVwjXkwTLepn6pekT6fN67HrFMZ8jGuaoAnaw7anw8gxt6ghDILQPrLdh70t5qbBNIOXise45h52dAc8O3P7+T22SWG0YtNTIhNK9GEINCTJp/eGfAWMEWyOZqt6n/PN3eXPZLsMHBETjeV1DygYKKstqzfp5
    username: AgC2nNroE0/qtHOF8Tly8y50YpDFMimsH+ohvZAMoCC3vM/q8UTIsTJAyKZJ6osNfxlvFDJYN7nE3PAr+NOY7vEpFXOP1/BytT/8bsnVrkIvAdfEcIxKGOa17aOFCO0hTpFoGy/9454eHeSRrvZUEzMfXmwpWI51QykWmRKIPFRqMMUeYS7kjs00LVKQOkrLkpI9nO1iG5EDqJ83+106I08yDk+bMpw+GW0QlkHf6VQn4Sfomb4p88sEYYBl9bV0SJcVpQMKgAeEBVKoLcyEX0eASObpfqld61czafF6NLXF5g6qlscRjp9+9BfEZbDtSciwi8TjRhGJth33fw6wV+Lv5uZpwy/Iq9TcITiw+NTmTTb/gyF5W2tmX2o9Awrt8YITc0d43CyE5NcNpGE1qLr7qdDjpc7Xxc7V8pE9aPPXJXzdw1Z1LVDEOKgKUlOYAn3RfGKSypJ4FOweYmP7X3SJnSrINdawTaBXIC8zP4FMbZBcN+48NYQiDhZjPLQictvQ6/VTBafp3GSNiAhogyJv4qeSnEuS8dokzwTfvg0/5HekvcM2j83ft6jUj59ARSuO7UekVVG4c/tmyUSDRt44KwPZn9Krp3dVz2cZovHjU7aaWKn72l1TL6c6lf85CYH9xenkIRhJHO77PR9uvB5JEm2Be7yCixIu97xk04Kykc1rPAse1PBtml4hfXb+Mpd4b7rXb9rFs/JP/iwCZczbcX4=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: brandwatch-postgres-credentials
      namespace: default
    type: kubernetes.io/basic-auth
