apiVersion: v1
data:
    password: ENC[AES256_GCM,data:dJMebvYwY8eAKZlvLGQA3YuYl2R1IAe0,iv:N9k221ctRiVxLBD5a2QVBsvebSQVv02MrSdlLGJpIhM=,tag:aLuTXdEtSyBEiJAXkm+3UA==,type:str]
    username: ENC[AES256_GCM,data:6qgVM68waZ0GmBHrQ30zIOEvh1hKtdgB,iv:JHXNP+RtFf2A11GQEqMFcp8rpUKrGdBj/d1dWCAkxtk=,tag:aJW5cJaIF7Txrre28l7C0Q==,type:str]
kind: Secret
metadata:
    labels:
        cnpg.io/reload: "true"
    name: brandwatch-postgres-credentials
    namespace: default
type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSFE5Vk01R0d2Yi9ST3Jr
            ZWJFMWZFVXR1TEJyeS9lL2V1TlZjaXIvQlFrClBLV0NMRE9DakxsMEFjaGRBWmFH
            ck1YSzVsNnUxei9PSEdKQ2FpVVhwZmcKLS0tIFBGdyt3UW9xQ3VlSU5QSTZJU0th
            UTMxaER5NVJpRGdnYnN2aldBTlJCV2cKWyGnE3G3lXu98MGbciXGT0dhuVVYW2Bh
            oYgH8d0OhxXjYM+xZTZLjhTbyKwpVsCAZuP8y9NG7SvIiv0Bm1Ph3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yfmz6900gp85qvse6pdd53h0c698jeh7pltmhtcpgse4duncqaqq9j2k23
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-12T20:35:02Z"
    mac: ENC[AES256_GCM,data:zD//0TmDrYrd5m/XnqnEe2mAYCNhcI1zByU+FD6/zVTkgMFZzFq/KiotF9Vuuw4Dj52H8uB+IMjPifosyrtzPMukIjE+pPSLk+HmiA7Mx2aPtyD/OkEY65dpBVnIYz3/U+PT6CdZVUyjgWxA0AaorftBhr8pXQhzAqBNejr4kuA=,iv:gt8MFxmHnxJPcgqFIF4Qa0SBJUW/cmnJQUP2swMtAZ8=,tag:5jLBB7vufzVB929qrdzzog==,type:str]
    version: 3.13.0
