apiVersion: v1
kind: Secret
metadata:
    name: brandwatch
    namespace: default
stringData:
    APP_KEY: ENC[AES256_GCM,data:61UF05A9PJIlRRpXSyRpMvD/zX2wz4QmzD3YwdyFIDJ/OheK4aepvkRWcTKs8X6BaATL,iv:kVTDJEQ0EO+yd++eUC5/0K3H8HZjZHzc3lwUWW7TPHo=,tag:XEpHt6tQxZh9jVaSPvSHRQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:AGcq0as3aFGY6uriVKgi1A==,iv:rblVa0ucUMLO8fsruydWmJDFW2UhQkQdrKH7EqI7ESg=,tag:B7h4ethsY2h9ZKlAtMVC7A==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:734SQl+N8EYzt4ZfVukSzA==,iv:UR2cHWabsbD56uTpo08pS8nlacmhGiyZFulIu+HbRx0=,tag:S4uKJfQzVTi9icxYdATOGQ==,type:str]
    BACKBLAZE_SECRET: ENC[AES256_GCM,data:yKh2hqV5FT0QyvqxThfGxmyx2G7JsMzZ7/ofDF2woA==,iv:3OpdWYSdGnjGwUxQwOGYAHBtefGGjAyQ6tmf1aqtGTs=,tag:xxtzulGx1RD/DpL/mVlO+A==,type:str]
    ROTATING_PROXY_URL: ENC[AES256_GCM,data:k0TB7rl8nO28aCqv+A4LJlMuD9CsyuS9Py2RqSRy7wA4U3YDn1n6jl55p7hxKqUOHmGF,iv:hWFcZOOytjvMLcEbKMKnoVjiuXLe2Y/Qxl9y1EXGOrg=,tag:/UZZ4Mnvc7b+ruxf4ssRBg==,type:str]
    ROTATING_PROXY_REBOOT_URL: ENC[AES256_GCM,data:f+24MLRsRDAuJtjmGvVl+b/mA2Ayw6wqQCXPQ1Lgj+JhkXNknIjC4lNQRb7HoimcYBzdh4NBPCVoBeuYfWKGaGUCfxmtta3xUzw=,iv:bNmbhWPbn2xWSt2wwO8iyFVVgClWkTd5I/WcrRvWZoY=,tag:VzVu7GcvAvk30K93obXZYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3U3dYUUpnRVcvWjhoWHJB
            M2RSQVRpWTVxRUwxalN6aGRRVFNQSWVhNEVnCmYwaEFkMFdKUzhhL1owNTlIWTVq
            cGMvL2RJT2l1Qmw2QWRmWVZ3ZXR2ZkkKLS0tIEtHa2FvU2JYMkpMWHdlNDlEbFQ3
            Tks2Y3VtSjVIS0F5VGs1YTFUN0NkSHcKvNha/Dsl+wyC2x2PjLeB0VxQEisYKiDG
            +YaOVHm8thlUJmRqWsnE/3mMjWnmdHkNIQZEdolXChkqUX6r1Zo+Cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yfmz6900gp85qvse6pdd53h0c698jeh7pltmhtcpgse4duncqaqq9j2k23
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T20:59:48Z"
    mac: ENC[AES256_GCM,data:4DcRBzGr5SbcR66mGRsxpWW66DdBQzixknR4osgPNJTf/EqHIkvu6UJloxStUQpECxtxM39SLG2XXNx9uZMV8gYotkG5a6uvF5LjPl4Sxx5tghqH77URpHdi/hKgy9xFfF50NiBMg6mIxBiONd33FtUbH9gOweFaG50K0qm3aZc=,iv:qpjktPIDLV+r8tEBN3WlBKUOzLbJpm+fC+HwN9mfTVk=,tag:WnmtK3lwU+zHiJv6MDeVHA==,type:str]
    version: 3.13.3
