apiVersion: v1
kind: Secret
metadata:
    name: brandwatch
    namespace: default
stringData:
    APP_KEY: ENC[AES256_GCM,data:61UF05A9PJIlRRpXSyRpMvD/zX2wz4QmzD3YwdyFIDJ/OheK4aepvkRWcTKs8X6BaATL,iv:kVTDJEQ0EO+yd++eUC5/0K3H8HZjZHzc3lwUWW7TPHo=,tag:XEpHt6tQxZh9jVaSPvSHRQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:AGcq0as3aFGY6uriVKgi1A==,iv:rblVa0ucUMLO8fsruydWmJDFW2UhQkQdrKH7EqI7ESg=,tag:B7h4ethsY2h9ZKlAtMVC7A==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:734SQl+N8EYzt4ZfVukSzA==,iv:UR2cHWabsbD56uTpo08pS8nlacmhGiyZFulIu+HbRx0=,tag:S4uKJfQzVTi9icxYdATOGQ==,type:str]
    BACKBLZE_SECRET: ENC[AES256_GCM,data:T5s5w1Vd0tQOXHdvaHU8u0Fb0nvUK0d2q70FFP28TA==,iv:KCla4xJXlGXH2c8m+JZtHXVmwpnNCIsKFLNleNfGeg0=,tag:w5nQ6ENCUg69UKYHyXvzMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3U3dYUUpnRVcvWjhoWHJB
            M2RSQVRpWTVxRUwxalN6aGRRVFNQSWVhNEVnCmYwaEFkMFdKUzhhL1owNTlIWTVq
            cGMvL2RJT2l1Qmw2QWRmWVZ3ZXR2ZkkKLS0tIEtHa2FvU2JYMkpMWHdlNDlEbFQ3
            Tks2Y3VtSjVIS0F5VGs1YTFUN0NkSHcKvNha/Dsl+wyC2x2PjLeB0VxQEisYKiDG
            +YaOVHm8thlUJmRqWsnE/3mMjWnmdHkNIQZEdolXChkqUX6r1Zo+Cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yfmz6900gp85qvse6pdd53h0c698jeh7pltmhtcpgse4duncqaqq9j2k23
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T18:08:44Z"
    mac: ENC[AES256_GCM,data:eRwtaiAUJSGjYaaJdc5B73OF8B/zz6qJq/huXGrqsefCDyHNh/dIhIP1GIzXIInpgGnnL0o1YfoW968WLEI5h3DnmA/523UcGx7j2nlo9ARVw+yqL0kgmx6bEdLEC+kbjxWnaJG8l/hI0jRCJONNbyxwTxK3DctXZs6V+N+jZMI=,iv:ZtTK7RsTEPUF6lzDawWnpU1JNDTIIB3t29CB3G1cPm8=,tag:3xJVlH1Xfb/1T88P0MHeKw==,type:str]
    version: 3.13.3
