apiVersion: v1
data:
    APP_KEY: ENC[AES256_GCM,data:+t6aqDOGZLQJsx1EvuHgIHq2bsTSK+BlsGHR53XZReYp7wrqiGD4KZX/ohV/ZFAOeirqIpiPXzvLoqqKOYGUr8gLG9g=,iv:7IdIiU1ZGTF/tpYWqXrtaro25U+i0o9KsK+kl2DroXw=,tag:mj/+9ILj0OofNscGO57Vxg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:rBk0rTQMGTbwIPZ+dIfk9/FVEDtsdgfP,iv:qqt4fEcprpOv78s8NDIRy/pwWzby4z2NqqGNWVb7unI=,tag:XfvImemDc6B8tXDyqdazrA==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:cWk9hypesxHqLmsF+doT/MLL3IkYFzSz,iv:nR27lEhEzWpaM8eL2O64H5Fh/aqSoTNxm9wRr9jWupI=,tag:E5fA5EgsgCbn9GyX6adX3A==,type:str]
kind: Secret
metadata:
    name: brandwatch
    namespace: default
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbW4xZmN4WmZlUllVeFZY
            MXpGNDY4dEZhb0drKzlmY0lPOHdMSVFwa21rCmIvMm1zVk1qQjl1RTc2dUw4WHla
            RTZEdkp2TzZRU0c5NlI1ZEt3cWdKY2cKLS0tIHJGc2VlSHp5ZCtGdWVyeUlmeitp
            RUxxSlp6YTFFSnBTUnUza3padnd3U2sKbxLiUcNc7CRt2geWA040rfpTQf3+xy0A
            N+abbX/aLjy06vqbzWNU+/FlpD4BX3B1lEBLHvPjZOPVIct7uEEFIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yfmz6900gp85qvse6pdd53h0c698jeh7pltmhtcpgse4duncqaqq9j2k23
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-12T20:35:02Z"
    mac: ENC[AES256_GCM,data:o6JLVB99cavHc7I50MoVZ2y2CNoFAyup1GuJ+vWEv5Qft5GqGXt6ui9uY5iyP3ML94TuLFKlIqOw+f84901YywU1uJvi94PvkrZnW1LpKnj1ImjqgFEvReO6ACLFc7OKkDm+k2OWP4WbA3TTeWt6YyC6VtyYOYANYDhalAxyqiU=,iv:5EoYKCIZ5yuEyeyTd6Oh5RD3i6tORKsZVPFByVJBjms=,tag:mkHOJtz/fkylpfnGJ4ZrWQ==,type:str]
    version: 3.13.0
