apiVersion: v1
kind: Secret
metadata:
    name: regcred
    namespace: default
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:m5hs9Mh/eHVS5BcsPT15CQg/YRUgv2lHf2bkZ/vFathNjOGfUqXDFEHfuSLh+aYaBp7e+FtY6B74/ff1GVQwbcXnDrbtPGv2FjvdZ3w6g/oPQkIwPW5F8Z0d/PpvcziZ4t6BThtISslaXHRWdWMKMtr/79+3q+RY959s8MNL5m71cRCGSKdMgJEgXxzzsOexFRnVuBQdADyzqeA=,iv:q3kG06FQ2cCShKcYa/h1LOTKJBrmCR7Vgd/xcGQBPko=,tag:q6HZDXZ4D/Vatyw3eDTRtw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYnFQUFk0d1ZJcktoaUlF
            V21QK1IxenJOYlQwVXpKdW5UenZVUVZQdGlnCldFVmhTNVlCdlhLeXFlOTcwUTgr
            SmQ5RlU0bDJtQ2RtNTdTaUNlaHFoZUUKLS0tIE1nOXYyRllDWUdGUFVrMG5jUWdy
            djU3VTRPL2tDYnN2aXFjZTIwOERKQ0EKm0bowrL3Ms6gNovjnm3oYE5RzogyP56C
            UFpiijaPUOd9INH7XDs4lBxGQ8FObrc+/HOi1FMPAnXB6bifcI4nqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yfmz6900gp85qvse6pdd53h0c698jeh7pltmhtcpgse4duncqaqq9j2k23
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-12T21:25:55Z"
    mac: ENC[AES256_GCM,data:nNrwyp5T9lcmfePS8nfeEg6kNqHPtgO4jdJXGk0t8Wlp93OXxQ4ecsxHiA0y6lW0E22je2vvVM86XCm4UIWG2yj0ospLZxpL58LGlMwnYFZtVkb3bFtvFn/Pg7m1kCAqY7Z2POow8KgzskxUdv6E6MQGMJyokeYQMhMk4VpkpSI=,iv:UP40ybJypieQPDxWm63uC+qySD9/jdsVmSu4ynIiB8Y=,tag:E5KBmpRgr5pNURsxqY8Nbw==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: regcred
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:m5hs9Mh/eHVS5BcsPT15CQg/YRUgv2lHf2bkZ/vFathNjOGfUqXDFEHfuSLh+aYaBp7e+FtY6B74/ff1GVQwbcXnDrbtPGv2FjvdZ3w6g/oPQkIwPW5F8Z0d/PpvcziZ4t6BThtISslaXHRWdWMKMtr/79+3q+RY959s8MNL5m71cRCGSKdMgJEgXxzzsOexFRnVuBQdADyzqeA=,iv:q3kG06FQ2cCShKcYa/h1LOTKJBrmCR7Vgd/xcGQBPko=,tag:q6HZDXZ4D/Vatyw3eDTRtw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYnFQUFk0d1ZJcktoaUlF
            V21QK1IxenJOYlQwVXpKdW5UenZVUVZQdGlnCldFVmhTNVlCdlhLeXFlOTcwUTgr
            SmQ5RlU0bDJtQ2RtNTdTaUNlaHFoZUUKLS0tIE1nOXYyRllDWUdGUFVrMG5jUWdy
            djU3VTRPL2tDYnN2aXFjZTIwOERKQ0EKm0bowrL3Ms6gNovjnm3oYE5RzogyP56C
            UFpiijaPUOd9INH7XDs4lBxGQ8FObrc+/HOi1FMPAnXB6bifcI4nqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yfmz6900gp85qvse6pdd53h0c698jeh7pltmhtcpgse4duncqaqq9j2k23
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-12T21:25:55Z"
    mac: ENC[AES256_GCM,data:nNrwyp5T9lcmfePS8nfeEg6kNqHPtgO4jdJXGk0t8Wlp93OXxQ4ecsxHiA0y6lW0E22je2vvVM86XCm4UIWG2yj0ospLZxpL58LGlMwnYFZtVkb3bFtvFn/Pg7m1kCAqY7Z2POow8KgzskxUdv6E6MQGMJyokeYQMhMk4VpkpSI=,iv:UP40ybJypieQPDxWm63uC+qySD9/jdsVmSu4ynIiB8Y=,tag:E5KBmpRgr5pNURsxqY8Nbw==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: velocita-db-backup-s3
    namespace: default
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:wRsnIjJ+SqXTifXJdtFku+v33Jwt6SXKhA==,iv:v0G0KM0R8N2d4ZhdGy7Sf+nvdPMpIHAKM1NqVeSGYHg=,tag:K7g7scZALfieXxHFCCf0PQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:nP//47MeaJLiNvKN6jjZgV2qm++NkUxJAzndsDItFA==,iv:xoXz28R2leF3CnmXKMO4Lk2w67neIYKfsOlXjGX9wEE=,tag:BuvIa1/D7DOyRcOY4EBeBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYnFQUFk0d1ZJcktoaUlF
            V21QK1IxenJOYlQwVXpKdW5UenZVUVZQdGlnCldFVmhTNVlCdlhLeXFlOTcwUTgr
            SmQ5RlU0bDJtQ2RtNTdTaUNlaHFoZUUKLS0tIE1nOXYyRllDWUdGUFVrMG5jUWdy
            djU3VTRPL2tDYnN2aXFjZTIwOERKQ0EKm0bowrL3Ms6gNovjnm3oYE5RzogyP56C
            UFpiijaPUOd9INH7XDs4lBxGQ8FObrc+/HOi1FMPAnXB6bifcI4nqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yfmz6900gp85qvse6pdd53h0c698jeh7pltmhtcpgse4duncqaqq9j2k23
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-12T21:25:55Z"
    mac: ENC[AES256_GCM,data:nNrwyp5T9lcmfePS8nfeEg6kNqHPtgO4jdJXGk0t8Wlp93OXxQ4ecsxHiA0y6lW0E22je2vvVM86XCm4UIWG2yj0ospLZxpL58LGlMwnYFZtVkb3bFtvFn/Pg7m1kCAqY7Z2POow8KgzskxUdv6E6MQGMJyokeYQMhMk4VpkpSI=,iv:UP40ybJypieQPDxWm63uC+qySD9/jdsVmSu4ynIiB8Y=,tag:E5KBmpRgr5pNURsxqY8Nbw==,type:str]
    version: 3.13.0
