---
apiVersion: mysql.sql.crossplane.io/v1alpha1
kind: Database
metadata:
  name: forgejo-db
spec:
  forProvider: {}
---
apiVersion: mysql.sql.crossplane.io/v1alpha1
kind: User
metadata:
  name: forgejo-db-user
spec:
  forProvider:
    passwordSecretRef:
      name: forgejo-credentials
      namespace: default
      key: DB_PASSWORD
---
apiVersion: mysql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: forgejo-db-grant
spec:
  forProvider:
    privileges:
      - ALL PRIVILEGES
    userRef:
      name: forgejo-db-user
    databaseRef:
      name: forgejo-db
