apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ZnEDBkfRNjCQU1AgRKvPo5g8AyQ2JjpTnlPyRXvfldBmZRCxBg3Z7wXrSN+JGwI4kmO+h2AMggs=,iv:qREpExatzEOyWRCTgsWnmU1ucZBOmMaMcsCHtRC0GfU=,tag:c4lWluSdrz1rvhjux2ACmg==,type:str]
    username: ENC[AES256_GCM,data:JKewLObSKDt8qwGHmUlct3emkYE=,iv:Ag3ymbxBAZis7eWhzuDiLrSxP1M7fUi2YC3HMA4IG2s=,tag:fjhpQAN2YNfAqqokXSb5Mg==,type:str]
kind: Secret
metadata:
    labels:
        cnpg.io/reload: "true"
    name: forgejo-postgres-credentials
    namespace: default
type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNV0lnZlYrakczNUdtTVVx
            WGV6U3V1TDkwZkJ0ZytrZmtWdjMxamJTbkhFCnBPL2t4elVuYXZ2S3R5MC94aS9Z
            U1FVTTlLVW5xeElRTW1wWXJ5bmZFUUEKLS0tIEZ0Z01ZM0VGUW5JTmR3aDZtVE1F
            MzE1Zk1DREE3VDVQMkl2ZDhKYWQ0Q0UKy1k1mGR15dcLKiI23vHCipe5Dj2xyjrV
            9fwQye2pBcn15dkmYC3c416A3SWPqfMwQ9pBZww7I33Q+2Bpoh0OxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yfmz6900gp85qvse6pdd53h0c698jeh7pltmhtcpgse4duncqaqq9j2k23
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-12T20:35:02Z"
    mac: ENC[AES256_GCM,data:ke4/3OuAhllTRWUu2zTyScKFwXZj5PJL/AhRSgePGwoHPzpy3SpYv5+2YGwk2ASHxw4UfgCN8FE4ot8GDYyVY//aqTBq0zntTnTrMjHn0vpG2Gx7I8tZoUeMK4tRjZ/+t1jtKoY489MpDAHoc3EnM6Wq0J3mssYXhNeXyr4yJZo=,iv:Hz0KXuWo/awc43DaObazZBeOcQ/91XaJJ08OEt6GmTk=,tag:8gvUUbLRs18Rv52UBOaqkg==,type:str]
    version: 3.13.0
