---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-postgres-credentials
  namespace: default
spec:
  encryptedData:
    password: AgCcWhejeGycwjPI30Bo0DfQSHsmavVVi42eFClye1Js0Ts0/FouDyTXNSox0euBiN3Om98D/24pus97w3cG1pcpqyhXuuKZR975MubbG/IxG8CwiZcJFkAbij5IBSIWGSo7sm3mdrxZAParrMHqVLBrw6uNuhc/9OibDf82OKtnLD/TrjeqIDVdIGW3fFJvSdy32iNkjjKvIWRgYjSDDhM/KjO8jVONgbZz5Se0Kg+nsueKU/vx4DWtxcje6TYAqcDGWqS8GrQAbwlrL3c8DIV6Q1AldA4L7juD5EzCfqtH99Hc0cTaSoMCsmYagvOAuJnVH+g4stYlQkJUzpZD7zcQVnHSMvQ55LfbBlJGm2rjIKYhXiEB8ANXe9fdG0JmqOX2xpzgUudBKsFD26wdWHKIghWkRJR5CQqSRJ7JsH/hgp/NGLU1RNy7d+Er757et8cf9LHszNf9Byue5f8WixvuvrnUotnBWVwtSRqUaM9coTfqnI/k2zZXCkk8IJVSj4wmir17QqFe10Uz2xvQ9CMiK/DqSxw+M4uSivv9XuOS6ykJDiB7ax8JEt43cEvjmvV8wVr+hz5jjdidms85R7Wc6FudxVZ5bcZvifjIJJtGaKWxgeNBpPHu+Yytfebmd9LSVp4tnTse1R04wE5RqQnWTBIaS14qh+MaAUsMobQftjjfrXWGcF+gUP+nWfhprbrCjXNbWHXY+vdu4ZGzJgeyTia2IJxm3GmZxRhJOQ+voMv5aAupOoXM
    username: AgBEatSrTCCCUOG3WgCw+d4ZEOrU66BIagVAE+0Vo6bUSjGoQNKNv/FpqVlSWLx4YQrekE263xE0TbMRCM51LoTlFQsl5Rz45WuPH84V1zHcYG+7dz9TZFiN7/bBmy3wEIT+ZXPt6dg/H11WujqBnhmKOtWOUMfc3AOOtGLgaHjxNB9l+rcQcUrYsIgnFzMXc+gtXKkzlSjlaqQP/MEjRF9xwHvsj6YVwNVTdSsRkwAJiHQkG+6c6ZpvCKjbBJ/aSItwTW/wgl6zpor99B59tDnXioet+Dmo6Oe+zM8j2jw7joLwBchlq01V/6C003YsxtI4ducPBqHWzBp9UGCWjR0lv7lN6mp1kl6j/QVs06fhW/bFGe1+xm8zHGA0WYSCQp3GlRYmVVIUWzeoCt3LiEI3FQayrY0pC8Fu32KN6Aw83yXwX9eAQIGp8VNDZC+nXPqAT47Tw3wR81i7csGx8/3aI35B7bbo9E7QF7T0i48skA1Qa18iqYYINBb3JCFxHVsu9z8S0n7pIUU+l+Uu2yayICKZzBQGA8hPa4YLLUr69D1dVrTgdBwAyFnRhrWJtSrR7fERkEsr/7PBA1AfYqxgwbRTfTSIoGON2eGghxSRJV5xrkTLMXZIcBZynzpIMIUwI7lk2Y/L+uPArnknB4W/82iyEmr1003mUzE0wxorD7C6bA+sIIvPyr/k+x99GjRPx/nUB1fq6aUC7Zv9le4=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: forgejo-postgres-credentials
      namespace: default
    type: kubernetes.io/basic-auth
