---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-postgres-credentials
  namespace: default
spec:
  encryptedData:
    password: AgBhCQ0SdvCcHWdyKR68RfIyQERJlEMnb+eQjEL5B+j2nJS6kPxxqqJzQ2oarkyP68VUdkHAQy4a7+nuJitwpu+pF/FNZoDuvC7j41s8V3RTgwL7wlw6C+FWpoWdeQjvMM+sN2+4nof0grmq64g4JQerr3ZXqY03Y5BVmREJ8xR29aPcWddJMpAVYPTlc3r0D2pZtlFNIZlGK2ulr10wDuwjEqWLcXstRiwhO0IAspeLbp2/D9sDmIJwBjc5len01veRM1pkI7J0hDI67/IzMxKMZb3TKk7uLvjbsVigDxB/3wrDPgk0rqUsRIfqqdX94O3gQ9nUqOpGZ6sq7YV9T7GAvWrWJSuCm9NmgoLLvi5dcJcSN1/kqx+ulVwIEa1mg8k+FsJmoMOhRoF0YzxO5tZXEzkzzwuTKMe8CbFIBD0WmVpJdnPyAha7R/9RtCKqhaY2e9U/NFu5KumL5TFlqsz4SMyyy6qpqW+sg91BJUsEQkK6vX1wwwYVzezKhNXqMmXIHcT2rlucYvLd3esQHIiakKLnpuEit0pxqFeGYdIKKGSWLNtsqqGc+LvmnD8vphn8wq5Vz89qT1f5KBgywPKH/CatDlXvdtlsP6SigH0HQ4llxM2WeoAAnLQVQpbbwCndPHEWIK0pu1BI3IQmZx0yIOfhq10m3BxAk38oMMMayImD8JCcrgxAcPS5O4GSiR9pLX6trh/T1vBZXMfGoMmTBPbUl/OYewKKjQZY6I3yWi7UBuZTL01J
    username: AgBLHzF7pCn2HnzCOyXoCQ3S5e0pMBor/0Cr8mS+Tp5Gdf1u7KtUuDxbAfqVAEjy/jQQia4VXjqs548Rn+ZIVKKnzZtVFhaTS9RRgCHdvUuzzPo2UFZ/mWRXPCbheHVM/XQsaiFCdx2RBym4RRMVycB28ouFspqNFB2f7YZJZ14aL7wTt0Wx1m87YYt2X41MAfaAfDkmDbzTCrpNjLbyFW2/aFRHfAoYgJ6V5Xdd+RRTcMGna0e8KRmkJ0tkP1TDflqcNou07EqJKgqYvm5oSZ87k8iEYdqL4ADhNabffvc2mPvQIah8zldQ//mKxY43NbsmZawL4fRq0mPHvUNxvXQD4P3V5kuVZtJaRszVQErYGSouV92xz/60aR1IDcCuvwaNC7aF/Rmgl3E6MuQMAVCmwddy4nJYXvQ59t5vf8vPSEFukviqtiVclMWTGw6UlB8OaJstYm8l2xaZqg1danqhcoM8a691t2CjjZW9K3QnkrOTmqVYWhs+fDZ0F/oaPO/jiOcmG3GoKAzr0vxxNMyJgIImvLRPPOgKYtohF2Ln7T/6je5RWsnr5p8LlQV+DT5hHaITNXLYkrvq81+rLSJMEq74tDy/3eREHqkwnDrkSwMz8M0UNL6i8DuDIXyyGeTi5QeZAKHrEXRTwkrJINlYnYq9zqX2x1YBl4AQd4sFFa0Yxa6xB5ZPRKf7QQ47pnizYJNZH8sfuPABPBQBsGU=
  template:
    metadata:
      name: forgejo-postgres-credentials
      namespace: default
    type: kubernetes.io/basic-auth
