---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-postgres-credentials
  namespace: default
spec:
  encryptedData:
    password: AgAN33mcPAsHjhad3nF6W5dS6/YabFM/vILwW6GQkVfNgfAcuQoT+D1N805vtb9UDf2a6kU4amc4eFbsPSN5tET6aCMex6HGVOnsD7bU1wFdnhwbI+0IHgwlRQBpt9aM23fJAOhx7uF6Lf4TfdUlD67a93AcNb8w5EFjWdWiFZapw00ToSEI3Vkz3tmInDItKKoBpMnr+FevDsn9P5X/gnrue3Lcl81kNvRb9mW266ylNuzMLFN3lqdPYBhpsgwraczx5A17mA44p/a+0I7vZHKQ11PkoyjC3yw3v0pYZwQY+B2yXPLfLIYEdCnoJJLXXDMPaC3LBOTkrjZGEl2kzQ0nhyCjbHxzvVSmwZ+ED+qg0MqBuJC8dPkRUGEChU6ZwVFa8ab2Ff7M0o7fJ5WnfJxgwFUsdmX1GwGTg763np0wFdxSnXBVyH1QhgKXaGMA5yTgYoZ0dW80V+PedbAOu5b50r8QGXZwETuR4cLjawoYmJ5fK3eXcWuOaR/h0cuU2SiiYNXxuJe6nxIWpNIIVsSa6i8xQ35PsfboHYLUt6yB38CTBgvB5DQLNq7xyBf/BR+qzqETLlyqcUy0sT/3225dovxgsaAUdlYsaO5Beu9vFD/2H+QiHSpyNoKl92IlVPdXD8CjcjvZdmYRvGWIi3vJEIb6s8Y4j/W/QPj5OyJFMHz1jlsyzaRTvt+WfFtkkQONrh+ESUNvwpdVGjJr4ilIs7u42xiebwkrs7RW13kbPid4T4TVDKTS
    username: AgBLy6FWCg9r39BkTtz+Qr+dW0BdJ1aec1c7SMcI7DGfsHYF0dgA06pmeL0H8qsIL8lBkWcKACg8xOVWzVtyjg53UjBH2I859e89tH3FBZyjowfx+7rCyAUTpYmSNktw3dLBCrmUMehdN65QTGnWDSH0E1pChI9IfApSrBYfrTphH0YGwsFkofJvGtE36xdIi1fx5uIqUl73wx/eDhD8QnjKgsePEM3DEOdVtr1Cfy89J5b4S2eutCWmpgLkap0zfwxqTjpm6tnT3xCspIHWBaO5D29V5hH/ZChmKfiimQ4f1tIW8upPev1xkDrEVG+oHWF5xiClR66QFMIDNEV2GV+pZ6ewgFGLptwYqu7lHvpveMt5fprReyNnF4gnASHrg2uj+CotxqlF/uC8DtbY0YkD/ow7a1I58MJnl6MP1rnwwYEcDgaUXxuSCVk4WqFgjCUmn8FdLv8MUd51MWHIzrzQdqZ8TOuH4WMBY88zlGXi0+DQzxEDFkXu5pko1Ecz1RkWJL8+9QJyqWr8Zjc4GEIyr8EE2JFsd6XRKUFaASby4nO4teFC89ndGCQMBnov/VuvHio0A0KBu3bCqKmPI9FGKkjg7V3lNBOi3dKrGmxxpJlSzHUFrxjSfdhovfVhlcY6ybOkKtkCPQN1Bxjxtwbk6uu3w1qI0pDri93FiA6sUmkaX+lpheba7rLhhviEqRLDINNTiM7w8ubbwpHNzJU=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: forgejo-postgres-credentials
      namespace: default
    type: kubernetes.io/basic-auth
