apiVersion: v1
kind: Secret
metadata:
    labels:
        cnpg.io/reload: "true"
    name: forgejo-postgres-credentials
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    password: ENC[AES256_GCM,data:y2sP2L9o5aQcHKY8JbIGKHHPRULo9I5jKv1KhLpawWiAxwx4o/ffJg==,iv:wcjPm6rUMbJfh55Lx5GDhiKLxmReHWSozwlyhNMCnO4=,tag:b/B6THQcnJtar4OnM7wLUA==,type:str]
    username: ENC[AES256_GCM,data:QlU2jgxjpy73u/5xnVOL,iv:/xGxXQcIfHGyvYDei0ijYxZf2ZdnMYPE7q7Y0YHbrNU=,tag:ZrJu46uzBSLwoOHFeXYRZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Q1IrdzREOEZRRFZjK3hC
            K1d2SXMvQUxyOUxaZWRQNUdKcFBBTDNLblhzCmxEY3R6cEJaVDJqdmxMVHRIOWRo
            aHBCMGJaNitpOXczN3FvRTFCZXI5THMKLS0tIHNyZVpWUUFzWWVGZ0toeUZHRlNW
            OWF5U1lNNnRjcGhBcjZ0QTZrb2E1YXcK8TE++HcZZBtMI5AO0BVPXAu1IEFi7gHB
            UM/u1m9HK0jTJEFm77qHFdK3klZPiZOXO8neoQyLvZd7Leyl7J+xAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yfmz6900gp85qvse6pdd53h0c698jeh7pltmhtcpgse4duncqaqq9j2k23
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T12:11:08Z"
    mac: ENC[AES256_GCM,data:3CkCG4fJ6jyPbbs0MX7gV5HQVZ+FrxF8+OBwR0+tTULldA+P8+9kCJMwNycRUZWlFGtuRdajVgQE1HB9pJzVcmdYejxyLNp5/EVvQMSQwx8oKDBm7yJbMBTPi0K51kFuELTywJOjvy5i10wwL+hRcUIjmNuZFuFAndQgIdpugqE=,iv:aPYOK+g+0chBVKJ5GKLtKBI2SYnkuEnO2C4Xtxq+wJE=,tag:YZsyMVE2InfCi2Rj8nD05g==,type:str]
    version: 3.13.0
