---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-runner-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hcloud-volumes
  resources:
    requests:
      storage: 100Gi
