---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-credentials
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgBFytL4+Xber+pycsYj3CPph5CkdMQUAcHsIuBhgFITlVHzm02S9gdLajenBTZHkPer5rNTK40liRgG08VTDLQCBLOvjoDjXbIFA2PP3fqVjU5W6y5qYyAG+VwCwHNHNFNKD9WOnlEMHrNIUEHtIvuvHIzD21ht22UhBDj18dvLHl/xoJ5iZ/RXzQ/woh5SCRs68qR2Xw8n5grPbMbq7GklOJp/PD6W9uZvZwhBlqImCP7aLG78xYjV4WGjl4vrJ49PzcxGY0HnroJZUkj1Bgxtv8Kg+hEZwwG31WxJNaOXHMMrw/dvdFRXnuVQfb2ra50J1m5BwXwWuECOmmYSsetNlP/kiBp6u7y495jeGSzMT3F2Xc886lf+hxvIuDU8p+2Mge32mB03rbxXmAuu+8TXZtyLi2Va8CzRm3sfawjDmqigq69QXLR5om8SsSCfHMy55U/o+ilQEd9yA1F7GWjtrpvaPWM7fkQ/EMFO40pzBsPhZ+7LfQZwWVHLscfSMUQWKhy13iFEJdyU8mwiODltxRA2feaKoEh9AUQS+hR1eyI6m1E4AEf1urzxZELAMQ9EmpECk5nlz9OVCwanGsL+AvUitiJ4+xVcjyTmJQVgZznN0f/f5SoHBCQ99Wc9kTvRNTYAplYZsgQ2HB+3dXHDAxzhxkCh97xRiE01UmvjGfgbMiAtTnptgeEcZKtR8OPOvQehKjCicLe47LNfkxCxqtsbB/GGTABHpPx7u+NPQYTdWX60Rqb/
    RUNNER_SECRET: AgAgLVbE5SWw1T3guGI5lKCQ6RJ7BvalS6FMqL0n1TXxuJpNlY3QKvXRfBiEmwQgZOv5wWQuEm3lO+eJIc2WYHNwsF1zf8Bp3X+WoSeYVGy6Rz9fXOmBV16YMgJaJj7tXojBDmbXe/zWFKvE4lUE3Qiyfuo5oIp/q7VhDFkxrlT4wy2ZmBC+Nhz95/EL2Iga4Hd6KkIPVYeYB/4tGwll0CY5CB7tvQGqwjfLsx9c/jNudxOTcqNmHb5N/DDFcx8S5WC/Y005y6cSsi8/7YlPpx0OKftgDJyNuE6efN47mosiqrYCackgETFDcNoTWprEXsNiuioyEwyIXZB3yDtVe5C4ZLgFtzC4/HRe5lpFOZ03aY+mtNf309H+AwljONcC/wPmlCKrh1Oio1VcsBb+KZ/4mA+dE6f5DzNvPYFknvtG6Sp8a00y86wkSzNBaTIwkmK+ftKzMV7yR4FSXJHcnpMf8m7as2KrT37iaB16IuFbX9N+3eO1b7FKm1PO1UuBx69I02WXjIPYO6RNwXaSzVkhnaL3NgwN4ShkPTGhT6G+ezegsr4s0/E6RDFxTsS6A//z9gFIv8wxf52D+b+Bf+xLx6gHXg+YE8PoVfBBl4S//IYo5Aag0aUMYmk+pOWqfCaEzd0JicFktmBMiMD8RunyFNwT0/yb8qGgxAxCkIrGEtv786kSWcf1zmPF3f9KJ4T2vHQV43y21hia3GSTGDnutp+/T35Vf+MMirK2xEvRvZhxsUYqxHSJ
  template:
    metadata:
      name: forgejo-credentials
      namespace: default
