---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgCFwKVCuBehGXJ0hIRMwmBrczoqLpU9LXytRuMmEyO/PpMrWa4lYhVn53TmhwwyVjIajxSMILRckgcAwjhnluNDrbJdyANawgBF8E0oVOCdslkGhnQmmnqKE7Xjuqr4HxH0NUtzVf1NkZmRNPUEdR/y4wdKdVjmPCU44gmIE+ODZXEryGpsnZCa+Mb2k9glrSZs63ohwKRVyYaaXvjtDyiY5l3beZrAM2BJH1CztD1PKO8fKpPPD1DT1UBJ0voCJnGyrHky4vwigywkO/k3zzwetJyKYYrjbeqvqxIgHasEy/dTXI+h05xoRnWlFRYyn8cJ/SpEvyTyWxzhC6QCH574sGv02td98DJ+WRLNwOEVKCU1n9r9W25ivmCtss07R4Ntes2U9VZ4bj7Vdks/KQUdYr+6rr/Cvb4oNJBPceCU+T0L0PL+834yD7jpt2/GoF9/SV3nCqX8c8mmMdpjbzVK2malh75j7UK7yuvue71HKfh05RMA5n3Y/6PhKu5tjz6vimdpYJjWVAYn8yPtuK2bqVKdO0A69Q63peG6gcGgozHgvSs4/56dbD5LzcPoTQouSoNh8/n9V/1vBTWzr1kH2AtdnTrncaI2wcY8frR8rD2ohX7sb3mYv9+NuaZR/uxq18DFrI9+3SgKq43LFY2Lt1Jhh5AVZYlUqIotVHdhl6Fuf/DH+XYZ5HGVW1SFcbAGpypBQzyWri5U51Nq9TjDv5o6eo11r+fRsFCQ5904uSLV1wJmY5sW
    RUNNER_SECRET: AgCsTLPezGBl9V4YAjCxHairieMcVz+xumNtYTF8mTakyfMybljVfU/hi2pQSajXOECRoutYo/Sl2RVQ+C6j6SBjaLk/kfVQTO3n+UyPG6/VDs38KC/p9ju2FaAhWU+mCfaZFgurs50qSPuSIp0c9nhZ4fFHNpJqtu9ffMwOdyW+gDZSDGVryRobYiBQlYqZOj2hKNo0Vo9NrWbAKMWUeSD4voMwq/OOVZbTbF2qVXMuN2Vb/O3truvUVdjX3Ves7/YonhBU6SrB2sy6nh1RsnKTRgrcY7Pv+8mxaulQg3K6eQ1TnAc5Xbr4wjtfQpkIHwSNXJROuBHgkKgetbZnxqLBQv627NHiX8Xw6Pe91k9S5Nx1b3NzlKS5yb84abiUF20hMo/1aBM4ouKK+rSyigsMyggdCMBNnEt/xBmD2gN0cy7oSUVS3E4b9n7MQFLYBDTWer0jdBUn3plx9NokLOdPrwLc7U6d+CvOslKwd5MeKZ+tmgzGqxAxTfAmO/6ZrE41wc2utTQKxXB7bIPGKZQVOTkvbD1LopwddK9Kpn0aSoV+mLrzOA/9+tWoP1uZdt26kYFiift2LNzinjsbSP46jNZ5DP+PkON+HZfEabNnkSciMOY3QsJXvpUEzK2hidfJr0kb4XhBz94s9lBjUQx5TuKQ4KsuyWu2X9cJuJ7pJmBRz2lGkmahApSHIhZP8QVIBMn8rpOw7PIpWegSR+iAVKK4ZROpA5cRsjzNRLCMPTqfJGHI9vNz
  template:
    metadata:
      name: forgejo
      namespace: default
