---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgCjnRO+Uzy88zSWxUAorjrQX7mA4qCccvuWX2IRHMjFsaS3ntacvGRUuwY6sPzr4EomtEHEcQ4WxInPlV2wfaHCMBlMsfN80tXAsCUrAy/07NMX6ncWdbzArMn+267GGMfVep/RBjMyxPksgeoQ5zw1U7t34KorwZlS3Taue/rfMWXVAmzf7pD6SmlzOz8wVjIsYqwD+XsPDo/cJUX8/7XOnCcIN6dmj06saRYSlJmxVho769hL0IWBDkpVQocCw/QenyOTMSnaeIJYTgpEaRRWv87kjdwH+9vFiB65enhGgZWJoFcaTEj5gpVtQOCNmNzOKSoLS4vJvTbsHOu6IMT0kSqwwAUaqO08/1n6YeVVr3uUIp01CIHJ9CSv+kpHC6x5r6OHVeWFQ3aQw5Msfb22cJvS08PqIzXLk0WJA6KI/FWI2YVHY3b/a2oqvS6ogXlYuxSQN/eMZ253k89BYhI5vAKkLJ9PVMCR/NQA0Xts5jRfXe8RDueqFBBsTWTiYoMOFzFyHPLCBVM+ptS5oRDCd2hda1XnhYj6tJejiQjLKz+TJF/4DEGcR7PEefeaXK+8G5vyYveq+1l5LlbtHz36f9eztEjUrYAxkeaHZ5q0A8+bWRo7BdiSIiaskT+cz5MfV33ieERY4zzDKqQfJVShGBW9tIh8blcBO5m3J45TgjVjMwtkCVyw8w6kJHSX3Iu6y6B5LAnTeHdtsCRGoGqhgq4q7Jr2EueXCEJm3HcUAodJqzYkg6/01C3dkoEd
    RUNNER_SECRET: AgAtvREJJ6/h6ig2InQ5Q3A5wM5Gcu1Ib0Zft3MaoqZn189x3xs7lXmo8lxlGqPiHL6XN1F0uSHaURy7WsSP6eaSz1ZAbPn1jTI7GKFi2YQyvvI5LtsYxNPUciKceDxAAPYIgym2ug8ppMH4xxfm9yndDOPPqSzxnfajmi6Y7Vo3Qm42Rao9PTw4zKKAbUFibAdyWhdkUo/0nK1azPGT29sMrWV4Nz0cA2Zv2Cqr7b3qs75eOHSvrd3i90VZfrA4v5sqr5YUVLhpVvlayTxe9UjrD7J5aAlmZ5zQZ6gSQ0hY8Pv8AFw9oNmZH6GAVDtiEogxkIrDrJSoroTCaHAqyo6G+L2G/vWQK7+j9pwpSZKrPNLgH+r/B/2gCKeN8zHaqmJdOx+7j081poTWvKbPJN7my6GYMYTz2Vn5zxfxdPBdXwFKbtZaggzi7M3p+7dvkCkVld2v/+2gofKBLDzq7Zo+C/k7Y86ce41dFTIf9gEY676+7uLSULMZIWCOwjO79wqMqJPkUgXIvAipwTkDPa21EWJyazv268icqmIodmclSooTTP2w5FQ+YsZX5VklLEI1LXnSj8oIJQQmEu75mFuoQuKooK1ZCAW8TCDeu6plP9oPQWWIv0BCOnVNPRHrbKg4lEMZuRPDbSg5ZmggoFrMv0bbqcLKDkPFpe18MeKoizR9/TEKxjC5DkqJTOPD6n0Ps2+c3MLVNlgJTbklVffL8H2lQUcia6o9JDW070BUcqMiI7Sb+Hm3gcw=
  template:
    metadata:
      name: forgejo
      namespace: default
