apiVersion: v1
kind: Secret
metadata:
    name: forgejo-credentials
    namespace: default
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:QcA363lry2AH2VwZkDXq9eSF9hxxEcjqIjdhc5881OJjGJ4dLS0lig==,iv:7FdrLBXYc6mFFC/qDEFrz3tvhIxHfpgqpwFhUKV1OXE=,tag:i3jYJIgAMDur3n2tJ1Mn8A==,type:str]
    RUNNER_SECRET: ENC[AES256_GCM,data:R/HVT9CMyDRd3NBeyXOq+pi1DueavKoo0BtQAbns+2f4B7hVyCyblg==,iv:XTUhIHwywhFLFIjXDeY+i74IXGEaBfTlVlyL58pwuS4=,tag:uD/+q6X9VF6/ogpJArGQeQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSXFNdUh5VWFOYWh6YXRK
            Qld6WTFWaE84Zi9hUWNBWlJUNXNNaGhlUUZNCngrQVdtTjJpbWs0YWozKzBvQkhh
            UWRpLzAzTWRnbjVrakZ0TXJFR0UvN3MKLS0tIGR3L2xyTkxRSERJYTRLZk84UG8w
            ZnVqNFNkd1dsUjM2Uzd5bTZXSHUwNXcKFBn+0+719S9ap2UGWKNuU3Z2UnvXgmsN
            wS4wNQDSxLKTBPit8WnpJtxwZGtedSRHW9hrUH8sDucu/TQZMIuZhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yfmz6900gp85qvse6pdd53h0c698jeh7pltmhtcpgse4duncqaqq9j2k23
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T09:43:49Z"
    mac: ENC[AES256_GCM,data:vLUCoS+fjg1y1Y8KH9E5b4BaicrrwBrNA0WbJlF88rJ+9EOmZluzOsm75se2FvCCEk0Qfrbopl80PGiEeDJ30mO230KR3yGA0AXiBX0Nw9gwm/6uGB+bp7ToZqlcZwVZkuEc0jMITa9u4OeKw73UOd3+5MGjBfUAcsGq0Zif2G8=,iv:tYoHE2qBLHqoHkMoCUhldpiDSdva8MFM8y5GRQOgM4Y=,tag:jQKfau7httWXvkdUD5mDCg==,type:str]
    version: 3.13.0
