apiVersion: v1
data:
    DB_PASSWORD: ENC[AES256_GCM,data:Ym4i6UQdnVpfCG6TwuQJG7amicR2dbisecfpdlaCeRa8j+qwxcfDHAjKltg+Nfm5pk1ezl1BkbA=,iv:ZGe01h0KBIzhRhjdWKcy3upN1YLhGddV0G4NrC4MN+M=,tag:KJNc1Tkcw1wk5IlGBDBkXQ==,type:str]
    RUNNER_SECRET: ENC[AES256_GCM,data:9zJAPbF4LBu0UtrMmEmkbFiZ+K4F6x1o4188ZPazCWaNVpEvaok8uC40Frg/6/R93ujYkb5sj+A=,iv:ww0QEHk9YxapvGWtK3IKOLlQdLr+SgeIBby0gl+EQdE=,tag:QRZJsQ3dcMEg7Mc9x7Vo6w==,type:str]
kind: Secret
metadata:
    name: forgejo-credentials
    namespace: default
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWEY4MzdSRWhmT1JURUxP
            TUpIME1QSmx1amwvdTNKa3pUbjdnYzJuK0VBClZVQVh5NnVkRFFEbUtkbG9BNWJZ
            b1piZG1DNFQwSUpJdm96K0J5aDhIV0kKLS0tIE9NSTBuRTl2c2krdC9FTVZlYytH
            MnpSb3pxQzA4QkZEekphZnpic2VQVFkKu/qBGxfKlGiLT9I0eIoxFzBLBL/ux1VZ
            7Y1f0ox9W+mtttIV9kCSDtgJXqc+8nXhtre11Ha9Z0leDNElJ1trnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yfmz6900gp85qvse6pdd53h0c698jeh7pltmhtcpgse4duncqaqq9j2k23
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-12T20:35:02Z"
    mac: ENC[AES256_GCM,data:vYLUmtC/D3Kn0fe46qNY5Pi97GirAnp9OGtYyc33z8P8Sov7AtLaxpJzDkOXMdh6FW3edYuaUuvhh4LGpYqeaujerZu/yQa5oEFh6tBu1Q9mpJ+Et555Z+dF57fQFEr92iWAMMH2tXxDWgteumIXaqVV4lyM65CCeN/EHCfuP/E=,iv:kd46bDuvzN/mJ3qgjB19hEDtG1edzw4vmR+11LSYwy0=,tag:0K1fmtQlBSFAmJgVkS+sVg==,type:str]
    version: 3.13.0
